services:
  awg-mesh-node:
    image: ghcr.io/coonfuuseed-paandaa/awg-mesh:latest
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    environment:
      - MESH_TOKEN=ca7ee971c8bb1b21b6579d20ca3bd8d1cb475fd4ed0b3a3d49cd0bf336556aed
      - MESH_MODE=endpoint
      - MESH_OVERLAY_IP=172.20.70.36
      - MESH_LISTEN_PORT=51820
    volumes:
      - /etc/awg-mesh:/etc/awg-mesh
      - /var/lib/awg-mesh:/var/lib/awg-mesh