services:
  awg-mesh-node:
    image: ghcr.io/coonfuuseed-paandaa/awg-mesh:latest
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    environment:
      - MESH_TOKEN=45edbd020663d28e284ca30103dfa0afe14d22d2dc8e7282c280727b30a669d4
      - MESH_MODE=master
      - MESH_OVERLAY_IP=172.20.70.2
      - MESH_LISTEN_PORT=51820
    volumes:
      - /etc/awg-mesh:/etc/awg-mesh
      - /var/lib/awg-mesh:/var/lib/awg-mesh