// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control_plane.proto

package control_plane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`                                  // [master], [client], [master, balancer, egress, ingress], etc.
	NodeCertPem   []byte                 `protobuf:"bytes,3,opt,name=node_cert_pem,json=nodeCertPem,proto3" json:"node_cert_pem,omitempty"` // mTLS identity (operator-provisioned at deploy time).
	NodeVersion   string                 `protobuf:"bytes,4,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,5,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"` // assigned overlay /32.
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterNodeRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RegisterNodeRequest) GetNodeCertPem() []byte {
	if x != nil {
		return x.NodeCertPem
	}
	return nil
}

func (x *RegisterNodeRequest) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *RegisterNodeRequest) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *RegisterNodeRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type RegisterNodeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accepted         bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason     string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // populated when accepted=false (e.g. role conflict, IP collision).
	RegisteredAtUnix int64                  `protobuf:"varint,3,opt,name=registered_at_unix,json=registeredAtUnix,proto3" json:"registered_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterNodeResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *RegisterNodeResponse) GetRegisteredAtUnix() int64 {
	if x != nil {
		return x.RegisteredAtUnix
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,2,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	Health        map[string]string      `protobuf:"bytes,3,rep,name=health,proto3" json:"health,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // role-specific health indicators
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HeartbeatRequest) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *HeartbeatRequest) GetHealth() map[string]string {
	if x != nil {
		return x.Health
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAtUnix  int64                  `protobuf:"varint,1,opt,name=server_at_unix,json=serverAtUnix,proto3" json:"server_at_unix,omitempty"`
	Stale         bool                   `protobuf:"varint,2,opt,name=stale,proto3" json:"stale,omitempty"` // true when control plane wants the node to re-register
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetServerAtUnix() int64 {
	if x != nil {
		return x.ServerAtUnix
	}
	return 0
}

func (x *HeartbeatResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

type StreamPeerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPeerListRequest) Reset() {
	*x = StreamPeerListRequest{}
	mi := &file_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPeerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPeerListRequest) ProtoMessage() {}

func (x *StreamPeerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPeerListRequest.ProtoReflect.Descriptor instead.
func (*StreamPeerListRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *StreamPeerListRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type PeerListUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectNode   string                 `protobuf:"bytes,1,opt,name=subject_node,json=subjectNode,proto3" json:"subject_node,omitempty"`
	Peers         []*PeerEntry           `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerListUpdate) Reset() {
	*x = PeerListUpdate{}
	mi := &file_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerListUpdate) ProtoMessage() {}

func (x *PeerListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerListUpdate.ProtoReflect.Descriptor instead.
func (*PeerListUpdate) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *PeerListUpdate) GetSubjectNode() string {
	if x != nil {
		return x.SubjectNode
	}
	return ""
}

func (x *PeerListUpdate) GetPeers() []*PeerEntry {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerListUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PeerEntry struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PeerName                string                 `protobuf:"bytes,1,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	PeerOverlayIp           string                 `protobuf:"bytes,2,opt,name=peer_overlay_ip,json=peerOverlayIp,proto3" json:"peer_overlay_ip,omitempty"`
	PeerPubkey              []byte                 `protobuf:"bytes,3,opt,name=peer_pubkey,json=peerPubkey,proto3" json:"peer_pubkey,omitempty"`
	PeerEndpointHost        string                 `protobuf:"bytes,4,opt,name=peer_endpoint_host,json=peerEndpointHost,proto3" json:"peer_endpoint_host,omitempty"` // for vanilla-WG client→master edge: master public IP+port
	AllowedIps              []string               `protobuf:"bytes,5,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`                     // partition for HA-2
	PersistentKeepaliveSecs int32                  `protobuf:"varint,6,opt,name=persistent_keepalive_secs,json=persistentKeepaliveSecs,proto3" json:"persistent_keepalive_secs,omitempty"`
	Protocol                string                 `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"` // "vanilla-wg" or "amneziawg"
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PeerEntry) Reset() {
	*x = PeerEntry{}
	mi := &file_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerEntry) ProtoMessage() {}

func (x *PeerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerEntry.ProtoReflect.Descriptor instead.
func (*PeerEntry) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *PeerEntry) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *PeerEntry) GetPeerOverlayIp() string {
	if x != nil {
		return x.PeerOverlayIp
	}
	return ""
}

func (x *PeerEntry) GetPeerPubkey() []byte {
	if x != nil {
		return x.PeerPubkey
	}
	return nil
}

func (x *PeerEntry) GetPeerEndpointHost() string {
	if x != nil {
		return x.PeerEndpointHost
	}
	return ""
}

func (x *PeerEntry) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerEntry) GetPersistentKeepaliveSecs() int32 {
	if x != nil {
		return x.PersistentKeepaliveSecs
	}
	return 0
}

func (x *PeerEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type StreamOwnershipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriberNode string                 `protobuf:"bytes,1,opt,name=subscriber_node,json=subscriberNode,proto3" json:"subscriber_node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamOwnershipRequest) Reset() {
	*x = StreamOwnershipRequest{}
	mi := &file_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOwnershipRequest) ProtoMessage() {}

func (x *StreamOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOwnershipRequest.ProtoReflect.Descriptor instead.
func (*StreamOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOwnershipRequest) GetSubscriberNode() string {
	if x != nil {
		return x.SubscriberNode
	}
	return ""
}

type OwnershipUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*OwnershipEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	FullSnapshot  bool                   `protobuf:"varint,3,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"` // true on first message after subscribe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnershipUpdate) Reset() {
	*x = OwnershipUpdate{}
	mi := &file_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipUpdate) ProtoMessage() {}

func (x *OwnershipUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipUpdate.ProtoReflect.Descriptor instead.
func (*OwnershipUpdate) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *OwnershipUpdate) GetEntries() []*OwnershipEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *OwnershipUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OwnershipUpdate) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

type OwnershipEntry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OverlayIp            string                 `protobuf:"bytes,1,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	OwningMaster         string                 `protobuf:"bytes,2,opt,name=owning_master,json=owningMaster,proto3" json:"owning_master,omitempty"`
	LastReassignedAtUnix int64                  `protobuf:"varint,3,opt,name=last_reassigned_at_unix,json=lastReassignedAtUnix,proto3" json:"last_reassigned_at_unix,omitempty"`
	Reason               string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // "scheduled" | "failover" | "operator-pinned"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OwnershipEntry) Reset() {
	*x = OwnershipEntry{}
	mi := &file_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipEntry) ProtoMessage() {}

func (x *OwnershipEntry) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipEntry.ProtoReflect.Descriptor instead.
func (*OwnershipEntry) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *OwnershipEntry) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *OwnershipEntry) GetOwningMaster() string {
	if x != nil {
		return x.OwningMaster
	}
	return ""
}

func (x *OwnershipEntry) GetLastReassignedAtUnix() int64 {
	if x != nil {
		return x.LastReassignedAtUnix
	}
	return 0
}

func (x *OwnershipEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RotateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tier              string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"` // "tier1" | "tier2" | "tier3"
	NewParams         *AWGParamsV2           `protobuf:"bytes,2,opt,name=new_params,json=newParams,proto3" json:"new_params,omitempty"`
	ApplyAtUnixMicros int64                  `protobuf:"varint,3,opt,name=apply_at_unix_micros,json=applyAtUnixMicros,proto3" json:"apply_at_unix_micros,omitempty"`
	RotationId        string                 `protobuf:"bytes,4,opt,name=rotation_id,json=rotationId,proto3" json:"rotation_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RotateRequest) Reset() {
	*x = RotateRequest{}
	mi := &file_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateRequest) ProtoMessage() {}

func (x *RotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateRequest.ProtoReflect.Descriptor instead.
func (*RotateRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *RotateRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *RotateRequest) GetNewParams() *AWGParamsV2 {
	if x != nil {
		return x.NewParams
	}
	return nil
}

func (x *RotateRequest) GetApplyAtUnixMicros() int64 {
	if x != nil {
		return x.ApplyAtUnixMicros
	}
	return 0
}

func (x *RotateRequest) GetRotationId() string {
	if x != nil {
		return x.RotationId
	}
	return ""
}

type RotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	RotationId    string                 `protobuf:"bytes,2,opt,name=rotation_id,json=rotationId,proto3" json:"rotation_id,omitempty"`
	Ack           bool                   `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // populated on rollback
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateResponse) Reset() {
	*x = RotateResponse{}
	mi := &file_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateResponse) ProtoMessage() {}

func (x *RotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateResponse.ProtoReflect.Descriptor instead.
func (*RotateResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *RotateResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RotateResponse) GetRotationId() string {
	if x != nil {
		return x.RotationId
	}
	return ""
}

func (x *RotateResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *RotateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AWGParamsV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jc            int32                  `protobuf:"varint,1,opt,name=jc,proto3" json:"jc,omitempty"`
	Jmin          int32                  `protobuf:"varint,2,opt,name=jmin,proto3" json:"jmin,omitempty"`
	Jmax          int32                  `protobuf:"varint,3,opt,name=jmax,proto3" json:"jmax,omitempty"`
	S1            int32                  `protobuf:"varint,4,opt,name=s1,proto3" json:"s1,omitempty"`
	S2            int32                  `protobuf:"varint,5,opt,name=s2,proto3" json:"s2,omitempty"`
	H1            uint32                 `protobuf:"varint,6,opt,name=h1,proto3" json:"h1,omitempty"`
	H2            uint32                 `protobuf:"varint,7,opt,name=h2,proto3" json:"h2,omitempty"`
	H3            uint32                 `protobuf:"varint,8,opt,name=h3,proto3" json:"h3,omitempty"`
	H4            uint32                 `protobuf:"varint,9,opt,name=h4,proto3" json:"h4,omitempty"`
	I1            []byte                 `protobuf:"bytes,10,opt,name=i1,proto3" json:"i1,omitempty"`
	I2            []byte                 `protobuf:"bytes,11,opt,name=i2,proto3" json:"i2,omitempty"`
	I3            []byte                 `protobuf:"bytes,12,opt,name=i3,proto3" json:"i3,omitempty"`
	I4            []byte                 `protobuf:"bytes,13,opt,name=i4,proto3" json:"i4,omitempty"`
	I5            []byte                 `protobuf:"bytes,14,opt,name=i5,proto3" json:"i5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AWGParamsV2) Reset() {
	*x = AWGParamsV2{}
	mi := &file_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWGParamsV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWGParamsV2) ProtoMessage() {}

func (x *AWGParamsV2) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWGParamsV2.ProtoReflect.Descriptor instead.
func (*AWGParamsV2) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *AWGParamsV2) GetJc() int32 {
	if x != nil {
		return x.Jc
	}
	return 0
}

func (x *AWGParamsV2) GetJmin() int32 {
	if x != nil {
		return x.Jmin
	}
	return 0
}

func (x *AWGParamsV2) GetJmax() int32 {
	if x != nil {
		return x.Jmax
	}
	return 0
}

func (x *AWGParamsV2) GetS1() int32 {
	if x != nil {
		return x.S1
	}
	return 0
}

func (x *AWGParamsV2) GetS2() int32 {
	if x != nil {
		return x.S2
	}
	return 0
}

func (x *AWGParamsV2) GetH1() uint32 {
	if x != nil {
		return x.H1
	}
	return 0
}

func (x *AWGParamsV2) GetH2() uint32 {
	if x != nil {
		return x.H2
	}
	return 0
}

func (x *AWGParamsV2) GetH3() uint32 {
	if x != nil {
		return x.H3
	}
	return 0
}

func (x *AWGParamsV2) GetH4() uint32 {
	if x != nil {
		return x.H4
	}
	return 0
}

func (x *AWGParamsV2) GetI1() []byte {
	if x != nil {
		return x.I1
	}
	return nil
}

func (x *AWGParamsV2) GetI2() []byte {
	if x != nil {
		return x.I2
	}
	return nil
}

func (x *AWGParamsV2) GetI3() []byte {
	if x != nil {
		return x.I3
	}
	return nil
}

func (x *AWGParamsV2) GetI4() []byte {
	if x != nil {
		return x.I4
	}
	return nil
}

func (x *AWGParamsV2) GetI5() []byte {
	if x != nil {
		return x.I5
	}
	return nil
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	IceCandidate  []byte                 `protobuf:"bytes,3,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"` // opaque ICE candidate blob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *SignalRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *SignalRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *SignalRequest) GetIceCandidate() []byte {
	if x != nil {
		return x.IceCandidate
	}
	return nil
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	IceCandidate  []byte                 `protobuf:"bytes,3,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *SignalResponse) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *SignalResponse) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *SignalResponse) GetIceCandidate() []byte {
	if x != nil {
		return x.IceCandidate
	}
	return nil
}

type StreamServiceRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngressNode   string                 `protobuf:"bytes,1,opt,name=ingress_node,json=ingressNode,proto3" json:"ingress_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamServiceRegistryRequest) Reset() {
	*x = StreamServiceRegistryRequest{}
	mi := &file_control_plane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamServiceRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamServiceRegistryRequest) ProtoMessage() {}

func (x *StreamServiceRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamServiceRegistryRequest.ProtoReflect.Descriptor instead.
func (*StreamServiceRegistryRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{15}
}

func (x *StreamServiceRegistryRequest) GetIngressNode() string {
	if x != nil {
		return x.IngressNode
	}
	return ""
}

type ServiceRegistryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceEntry        `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistryUpdate) Reset() {
	*x = ServiceRegistryUpdate{}
	mi := &file_control_plane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistryUpdate) ProtoMessage() {}

func (x *ServiceRegistryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistryUpdate.ProtoReflect.Descriptor instead.
func (*ServiceRegistryUpdate) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceRegistryUpdate) GetServices() []*ServiceEntry {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceRegistryUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ServiceEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TargetOverlayIp string                 `protobuf:"bytes,2,opt,name=target_overlay_ip,json=targetOverlayIp,proto3" json:"target_overlay_ip,omitempty"`
	TargetPort      int32                  `protobuf:"varint,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp" | "udp"
	Mode            string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`         // "sni_passthrough" | "tls_terminate" | "tcp_forward" | "udp_forward"
	Tenant          string                 `protobuf:"bytes,6,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Http3           bool                   `protobuf:"varint,7,opt,name=http3,proto3" json:"http3,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceEntry) Reset() {
	*x = ServiceEntry{}
	mi := &file_control_plane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEntry) ProtoMessage() {}

func (x *ServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEntry.ProtoReflect.Descriptor instead.
func (*ServiceEntry) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceEntry) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServiceEntry) GetTargetOverlayIp() string {
	if x != nil {
		return x.TargetOverlayIp
	}
	return ""
}

func (x *ServiceEntry) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ServiceEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServiceEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ServiceEntry) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ServiceEntry) GetHttp3() bool {
	if x != nil {
		return x.Http3
	}
	return false
}

type QueryAuditRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SinceUnix       int64                  `protobuf:"varint,1,opt,name=since_unix,json=sinceUnix,proto3" json:"since_unix,omitempty"`
	UntilUnix       int64                  `protobuf:"varint,2,opt,name=until_unix,json=untilUnix,proto3" json:"until_unix,omitempty"`
	EventTypeFilter string                 `protobuf:"bytes,3,opt,name=event_type_filter,json=eventTypeFilter,proto3" json:"event_type_filter,omitempty"`
	NodeFilter      string                 `protobuf:"bytes,4,opt,name=node_filter,json=nodeFilter,proto3" json:"node_filter,omitempty"`
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryAuditRequest) Reset() {
	*x = QueryAuditRequest{}
	mi := &file_control_plane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditRequest) ProtoMessage() {}

func (x *QueryAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{18}
}

func (x *QueryAuditRequest) GetSinceUnix() int64 {
	if x != nil {
		return x.SinceUnix
	}
	return 0
}

func (x *QueryAuditRequest) GetUntilUnix() int64 {
	if x != nil {
		return x.UntilUnix
	}
	return 0
}

func (x *QueryAuditRequest) GetEventTypeFilter() string {
	if x != nil {
		return x.EventTypeFilter
	}
	return ""
}

func (x *QueryAuditRequest) GetNodeFilter() string {
	if x != nil {
		return x.NodeFilter
	}
	return ""
}

func (x *QueryAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnix        int64                  `protobuf:"varint,1,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Actor         string                 `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_control_plane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{19}
}

func (x *AuditEntry) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *AuditEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEntry) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AuditEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type DecommissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	DrainSeconds  int32                  `protobuf:"varint,2,opt,name=drain_seconds,json=drainSeconds,proto3" json:"drain_seconds,omitempty"` // gRPC drain window before peer removal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecommissionRequest) Reset() {
	*x = DecommissionRequest{}
	mi := &file_control_plane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecommissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecommissionRequest) ProtoMessage() {}

func (x *DecommissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecommissionRequest.ProtoReflect.Descriptor instead.
func (*DecommissionRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{20}
}

func (x *DecommissionRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *DecommissionRequest) GetDrainSeconds() int32 {
	if x != nil {
		return x.DrainSeconds
	}
	return 0
}

type DecommissionResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Success                bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReassignedOverlayCount int32                  `protobuf:"varint,2,opt,name=reassigned_overlay_count,json=reassignedOverlayCount,proto3" json:"reassigned_overlay_count,omitempty"`
	Error                  string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DecommissionResponse) Reset() {
	*x = DecommissionResponse{}
	mi := &file_control_plane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecommissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecommissionResponse) ProtoMessage() {}

func (x *DecommissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecommissionResponse.ProtoReflect.Descriptor instead.
func (*DecommissionResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{21}
}

func (x *DecommissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DecommissionResponse) GetReassignedOverlayCount() int32 {
	if x != nil {
		return x.ReassignedOverlayCount
	}
	return 0
}

func (x *DecommissionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCertRequest) Reset() {
	*x = StreamCertRequest{}
	mi := &file_control_plane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCertRequest) ProtoMessage() {}

func (x *StreamCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCertRequest.ProtoReflect.Descriptor instead.
func (*StreamCertRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{22}
}

func (x *StreamCertRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type CertUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertPem        []byte                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem         []byte                 `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	ValidFromUnix  int64                  `protobuf:"varint,3,opt,name=valid_from_unix,json=validFromUnix,proto3" json:"valid_from_unix,omitempty"`
	ValidUntilUnix int64                  `protobuf:"varint,4,opt,name=valid_until_unix,json=validUntilUnix,proto3" json:"valid_until_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertUpdate) Reset() {
	*x = CertUpdate{}
	mi := &file_control_plane_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertUpdate) ProtoMessage() {}

func (x *CertUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertUpdate.ProtoReflect.Descriptor instead.
func (*CertUpdate) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{23}
}

func (x *CertUpdate) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *CertUpdate) GetKeyPem() []byte {
	if x != nil {
		return x.KeyPem
	}
	return nil
}

func (x *CertUpdate) GetValidFromUnix() int64 {
	if x != nil {
		return x.ValidFromUnix
	}
	return 0
}

func (x *CertUpdate) GetValidUntilUnix() int64 {
	if x != nil {
		return x.ValidUntilUnix
	}
	return 0
}

var File_control_plane_proto protoreflect.FileDescriptor

const file_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x13control_plane.proto\x12\x18awgmesh.control_plane.v1\"\xc6\x01\n" +
	"\x13RegisterNodeRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\"\n" +
	"\rnode_cert_pem\x18\x03 \x01(\fR\vnodeCertPem\x12!\n" +
	"\fnode_version\x18\x04 \x01(\tR\vnodeVersion\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x05 \x01(\tR\toverlayIp\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\"\x85\x01\n" +
	"\x14RegisterNodeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x12,\n" +
	"\x12registered_at_unix\x18\x03 \x01(\x03R\x10registeredAtUnix\"\xdc\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12 \n" +
	"\fsent_at_unix\x18\x02 \x01(\x03R\n" +
	"sentAtUnix\x12N\n" +
	"\x06health\x18\x03 \x03(\v26.awgmesh.control_plane.v1.HeartbeatRequest.HealthEntryR\x06health\x1a9\n" +
	"\vHealthEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x11HeartbeatResponse\x12$\n" +
	"\x0eserver_at_unix\x18\x01 \x01(\x03R\fserverAtUnix\x12\x14\n" +
	"\x05stale\x18\x02 \x01(\bR\x05stale\"4\n" +
	"\x15StreamPeerListRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"\x88\x01\n" +
	"\x0ePeerListUpdate\x12!\n" +
	"\fsubject_node\x18\x01 \x01(\tR\vsubjectNode\x129\n" +
	"\x05peers\x18\x02 \x03(\v2#.awgmesh.control_plane.v1.PeerEntryR\x05peers\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\x98\x02\n" +
	"\tPeerEntry\x12\x1b\n" +
	"\tpeer_name\x18\x01 \x01(\tR\bpeerName\x12&\n" +
	"\x0fpeer_overlay_ip\x18\x02 \x01(\tR\rpeerOverlayIp\x12\x1f\n" +
	"\vpeer_pubkey\x18\x03 \x01(\fR\n" +
	"peerPubkey\x12,\n" +
	"\x12peer_endpoint_host\x18\x04 \x01(\tR\x10peerEndpointHost\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x03(\tR\n" +
	"allowedIps\x12:\n" +
	"\x19persistent_keepalive_secs\x18\x06 \x01(\x05R\x17persistentKeepaliveSecs\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\"A\n" +
	"\x16StreamOwnershipRequest\x12'\n" +
	"\x0fsubscriber_node\x18\x01 \x01(\tR\x0esubscriberNode\"\x94\x01\n" +
	"\x0fOwnershipUpdate\x12B\n" +
	"\aentries\x18\x01 \x03(\v2(.awgmesh.control_plane.v1.OwnershipEntryR\aentries\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12#\n" +
	"\rfull_snapshot\x18\x03 \x01(\bR\ffullSnapshot\"\xa3\x01\n" +
	"\x0eOwnershipEntry\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x01 \x01(\tR\toverlayIp\x12#\n" +
	"\rowning_master\x18\x02 \x01(\tR\fowningMaster\x125\n" +
	"\x17last_reassigned_at_unix\x18\x03 \x01(\x03R\x14lastReassignedAtUnix\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xbb\x01\n" +
	"\rRotateRequest\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12D\n" +
	"\n" +
	"new_params\x18\x02 \x01(\v2%.awgmesh.control_plane.v1.AWGParamsV2R\tnewParams\x12/\n" +
	"\x14apply_at_unix_micros\x18\x03 \x01(\x03R\x11applyAtUnixMicros\x12\x1f\n" +
	"\vrotation_id\x18\x04 \x01(\tR\n" +
	"rotationId\"v\n" +
	"\x0eRotateResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1f\n" +
	"\vrotation_id\x18\x02 \x01(\tR\n" +
	"rotationId\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\bR\x03ack\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xf5\x01\n" +
	"\vAWGParamsV2\x12\x0e\n" +
	"\x02jc\x18\x01 \x01(\x05R\x02jc\x12\x12\n" +
	"\x04jmin\x18\x02 \x01(\x05R\x04jmin\x12\x12\n" +
	"\x04jmax\x18\x03 \x01(\x05R\x04jmax\x12\x0e\n" +
	"\x02s1\x18\x04 \x01(\x05R\x02s1\x12\x0e\n" +
	"\x02s2\x18\x05 \x01(\x05R\x02s2\x12\x0e\n" +
	"\x02h1\x18\x06 \x01(\rR\x02h1\x12\x0e\n" +
	"\x02h2\x18\a \x01(\rR\x02h2\x12\x0e\n" +
	"\x02h3\x18\b \x01(\rR\x02h3\x12\x0e\n" +
	"\x02h4\x18\t \x01(\rR\x02h4\x12\x0e\n" +
	"\x02i1\x18\n" +
	" \x01(\fR\x02i1\x12\x0e\n" +
	"\x02i2\x18\v \x01(\fR\x02i2\x12\x0e\n" +
	"\x02i3\x18\f \x01(\fR\x02i3\x12\x0e\n" +
	"\x02i4\x18\r \x01(\fR\x02i4\x12\x0e\n" +
	"\x02i5\x18\x0e \x01(\fR\x02i5\"j\n" +
	"\rSignalRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\x12#\n" +
	"\rice_candidate\x18\x03 \x01(\fR\ficeCandidate\"k\n" +
	"\x0eSignalResponse\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\x12#\n" +
	"\rice_candidate\x18\x03 \x01(\fR\ficeCandidate\"A\n" +
	"\x1cStreamServiceRegistryRequest\x12!\n" +
	"\fingress_node\x18\x01 \x01(\tR\vingressNode\"u\n" +
	"\x15ServiceRegistryUpdate\x12B\n" +
	"\bservices\x18\x01 \x03(\v2&.awgmesh.control_plane.v1.ServiceEntryR\bservices\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\xd5\x01\n" +
	"\fServiceEntry\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12*\n" +
	"\x11target_overlay_ip\x18\x02 \x01(\tR\x0ftargetOverlayIp\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\x05R\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x16\n" +
	"\x06tenant\x18\x06 \x01(\tR\x06tenant\x12\x14\n" +
	"\x05http3\x18\a \x01(\bR\x05http3\"\xb4\x01\n" +
	"\x11QueryAuditRequest\x12\x1d\n" +
	"\n" +
	"since_unix\x18\x01 \x01(\x03R\tsinceUnix\x12\x1d\n" +
	"\n" +
	"until_unix\x18\x02 \x01(\x03R\tuntilUnix\x12*\n" +
	"\x11event_type_filter\x18\x03 \x01(\tR\x0feventTypeFilter\x12\x1f\n" +
	"\vnode_filter\x18\x04 \x01(\tR\n" +
	"nodeFilter\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x8f\x01\n" +
	"\n" +
	"AuditEntry\x12\x17\n" +
	"\ats_unix\x18\x01 \x01(\x03R\x06tsUnix\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x14\n" +
	"\x05actor\x18\x05 \x01(\tR\x05actor\"W\n" +
	"\x13DecommissionRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\rdrain_seconds\x18\x02 \x01(\x05R\fdrainSeconds\"\x80\x01\n" +
	"\x14DecommissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\x18reassigned_overlay_count\x18\x02 \x01(\x05R\x16reassignedOverlayCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"0\n" +
	"\x11StreamCertRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"\x92\x01\n" +
	"\n" +
	"CertUpdate\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\fR\x06keyPem\x12&\n" +
	"\x0fvalid_from_unix\x18\x03 \x01(\x03R\rvalidFromUnix\x12(\n" +
	"\x10valid_until_unix\x18\x04 \x01(\x03R\x0evalidUntilUnix2\xe7\b\n" +
	"\fControlPlane\x12m\n" +
	"\fRegisterNode\x12-.awgmesh.control_plane.v1.RegisterNodeRequest\x1a..awgmesh.control_plane.v1.RegisterNodeResponse\x12h\n" +
	"\tHeartbeat\x12*.awgmesh.control_plane.v1.HeartbeatRequest\x1a+.awgmesh.control_plane.v1.HeartbeatResponse(\x010\x01\x12m\n" +
	"\x0eStreamPeerList\x12/.awgmesh.control_plane.v1.StreamPeerListRequest\x1a(.awgmesh.control_plane.v1.PeerListUpdate0\x01\x12p\n" +
	"\x0fStreamOwnership\x120.awgmesh.control_plane.v1.StreamOwnershipRequest\x1a).awgmesh.control_plane.v1.OwnershipUpdate0\x01\x12p\n" +
	"\x17RotateAWGParamsMeshWide\x12'.awgmesh.control_plane.v1.RotateRequest\x1a(.awgmesh.control_plane.v1.RotateResponse(\x010\x01\x12g\n" +
	"\x0eSignalExchange\x12'.awgmesh.control_plane.v1.SignalRequest\x1a(.awgmesh.control_plane.v1.SignalResponse(\x010\x01\x12\x82\x01\n" +
	"\x15StreamServiceRegistry\x126.awgmesh.control_plane.v1.StreamServiceRegistryRequest\x1a/.awgmesh.control_plane.v1.ServiceRegistryUpdate0\x01\x12a\n" +
	"\n" +
	"QueryAudit\x12+.awgmesh.control_plane.v1.QueryAuditRequest\x1a$.awgmesh.control_plane.v1.AuditEntry0\x01\x12q\n" +
	"\x10DecommissionNode\x12-.awgmesh.control_plane.v1.DecommissionRequest\x1a..awgmesh.control_plane.v1.DecommissionResponse\x12g\n" +
	"\x10StreamCertUpdate\x12+.awgmesh.control_plane.v1.StreamCertRequest\x1a$.awgmesh.control_plane.v1.CertUpdate0\x01B=Z;github.com/coonfuuseed-paandaa/awg-mesh/proto/control_planeb\x06proto3"

var (
	file_control_plane_proto_rawDescOnce sync.Once
	file_control_plane_proto_rawDescData []byte
)

func file_control_plane_proto_rawDescGZIP() []byte {
	file_control_plane_proto_rawDescOnce.Do(func() {
		file_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)))
	})
	return file_control_plane_proto_rawDescData
}

var file_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_control_plane_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),          // 0: awgmesh.control_plane.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),         // 1: awgmesh.control_plane.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),             // 2: awgmesh.control_plane.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 3: awgmesh.control_plane.v1.HeartbeatResponse
	(*StreamPeerListRequest)(nil),        // 4: awgmesh.control_plane.v1.StreamPeerListRequest
	(*PeerListUpdate)(nil),               // 5: awgmesh.control_plane.v1.PeerListUpdate
	(*PeerEntry)(nil),                    // 6: awgmesh.control_plane.v1.PeerEntry
	(*StreamOwnershipRequest)(nil),       // 7: awgmesh.control_plane.v1.StreamOwnershipRequest
	(*OwnershipUpdate)(nil),              // 8: awgmesh.control_plane.v1.OwnershipUpdate
	(*OwnershipEntry)(nil),               // 9: awgmesh.control_plane.v1.OwnershipEntry
	(*RotateRequest)(nil),                // 10: awgmesh.control_plane.v1.RotateRequest
	(*RotateResponse)(nil),               // 11: awgmesh.control_plane.v1.RotateResponse
	(*AWGParamsV2)(nil),                  // 12: awgmesh.control_plane.v1.AWGParamsV2
	(*SignalRequest)(nil),                // 13: awgmesh.control_plane.v1.SignalRequest
	(*SignalResponse)(nil),               // 14: awgmesh.control_plane.v1.SignalResponse
	(*StreamServiceRegistryRequest)(nil), // 15: awgmesh.control_plane.v1.StreamServiceRegistryRequest
	(*ServiceRegistryUpdate)(nil),        // 16: awgmesh.control_plane.v1.ServiceRegistryUpdate
	(*ServiceEntry)(nil),                 // 17: awgmesh.control_plane.v1.ServiceEntry
	(*QueryAuditRequest)(nil),            // 18: awgmesh.control_plane.v1.QueryAuditRequest
	(*AuditEntry)(nil),                   // 19: awgmesh.control_plane.v1.AuditEntry
	(*DecommissionRequest)(nil),          // 20: awgmesh.control_plane.v1.DecommissionRequest
	(*DecommissionResponse)(nil),         // 21: awgmesh.control_plane.v1.DecommissionResponse
	(*StreamCertRequest)(nil),            // 22: awgmesh.control_plane.v1.StreamCertRequest
	(*CertUpdate)(nil),                   // 23: awgmesh.control_plane.v1.CertUpdate
	nil,                                  // 24: awgmesh.control_plane.v1.HeartbeatRequest.HealthEntry
}
var file_control_plane_proto_depIdxs = []int32{
	24, // 0: awgmesh.control_plane.v1.HeartbeatRequest.health:type_name -> awgmesh.control_plane.v1.HeartbeatRequest.HealthEntry
	6,  // 1: awgmesh.control_plane.v1.PeerListUpdate.peers:type_name -> awgmesh.control_plane.v1.PeerEntry
	9,  // 2: awgmesh.control_plane.v1.OwnershipUpdate.entries:type_name -> awgmesh.control_plane.v1.OwnershipEntry
	12, // 3: awgmesh.control_plane.v1.RotateRequest.new_params:type_name -> awgmesh.control_plane.v1.AWGParamsV2
	17, // 4: awgmesh.control_plane.v1.ServiceRegistryUpdate.services:type_name -> awgmesh.control_plane.v1.ServiceEntry
	0,  // 5: awgmesh.control_plane.v1.ControlPlane.RegisterNode:input_type -> awgmesh.control_plane.v1.RegisterNodeRequest
	2,  // 6: awgmesh.control_plane.v1.ControlPlane.Heartbeat:input_type -> awgmesh.control_plane.v1.HeartbeatRequest
	4,  // 7: awgmesh.control_plane.v1.ControlPlane.StreamPeerList:input_type -> awgmesh.control_plane.v1.StreamPeerListRequest
	7,  // 8: awgmesh.control_plane.v1.ControlPlane.StreamOwnership:input_type -> awgmesh.control_plane.v1.StreamOwnershipRequest
	10, // 9: awgmesh.control_plane.v1.ControlPlane.RotateAWGParamsMeshWide:input_type -> awgmesh.control_plane.v1.RotateRequest
	13, // 10: awgmesh.control_plane.v1.ControlPlane.SignalExchange:input_type -> awgmesh.control_plane.v1.SignalRequest
	15, // 11: awgmesh.control_plane.v1.ControlPlane.StreamServiceRegistry:input_type -> awgmesh.control_plane.v1.StreamServiceRegistryRequest
	18, // 12: awgmesh.control_plane.v1.ControlPlane.QueryAudit:input_type -> awgmesh.control_plane.v1.QueryAuditRequest
	20, // 13: awgmesh.control_plane.v1.ControlPlane.DecommissionNode:input_type -> awgmesh.control_plane.v1.DecommissionRequest
	22, // 14: awgmesh.control_plane.v1.ControlPlane.StreamCertUpdate:input_type -> awgmesh.control_plane.v1.StreamCertRequest
	1,  // 15: awgmesh.control_plane.v1.ControlPlane.RegisterNode:output_type -> awgmesh.control_plane.v1.RegisterNodeResponse
	3,  // 16: awgmesh.control_plane.v1.ControlPlane.Heartbeat:output_type -> awgmesh.control_plane.v1.HeartbeatResponse
	5,  // 17: awgmesh.control_plane.v1.ControlPlane.StreamPeerList:output_type -> awgmesh.control_plane.v1.PeerListUpdate
	8,  // 18: awgmesh.control_plane.v1.ControlPlane.StreamOwnership:output_type -> awgmesh.control_plane.v1.OwnershipUpdate
	11, // 19: awgmesh.control_plane.v1.ControlPlane.RotateAWGParamsMeshWide:output_type -> awgmesh.control_plane.v1.RotateResponse
	14, // 20: awgmesh.control_plane.v1.ControlPlane.SignalExchange:output_type -> awgmesh.control_plane.v1.SignalResponse
	16, // 21: awgmesh.control_plane.v1.ControlPlane.StreamServiceRegistry:output_type -> awgmesh.control_plane.v1.ServiceRegistryUpdate
	19, // 22: awgmesh.control_plane.v1.ControlPlane.QueryAudit:output_type -> awgmesh.control_plane.v1.AuditEntry
	21, // 23: awgmesh.control_plane.v1.ControlPlane.DecommissionNode:output_type -> awgmesh.control_plane.v1.DecommissionResponse
	23, // 24: awgmesh.control_plane.v1.ControlPlane.StreamCertUpdate:output_type -> awgmesh.control_plane.v1.CertUpdate
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_control_plane_proto_init() }
func file_control_plane_proto_init() {
	if File_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_proto_goTypes,
		DependencyIndexes: file_control_plane_proto_depIdxs,
		MessageInfos:      file_control_plane_proto_msgTypes,
	}.Build()
	File_control_plane_proto = out.File
	file_control_plane_proto_goTypes = nil
	file_control_plane_proto_depIdxs = nil
}
