// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: control_plane.proto

package control_plane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_RegisterNode_FullMethodName            = "/awgmesh.control_plane.v1.ControlPlane/RegisterNode"
	ControlPlane_Heartbeat_FullMethodName               = "/awgmesh.control_plane.v1.ControlPlane/Heartbeat"
	ControlPlane_StreamPeerList_FullMethodName          = "/awgmesh.control_plane.v1.ControlPlane/StreamPeerList"
	ControlPlane_StreamOwnership_FullMethodName         = "/awgmesh.control_plane.v1.ControlPlane/StreamOwnership"
	ControlPlane_RotateAWGParamsMeshWide_FullMethodName = "/awgmesh.control_plane.v1.ControlPlane/RotateAWGParamsMeshWide"
	ControlPlane_SignalExchange_FullMethodName          = "/awgmesh.control_plane.v1.ControlPlane/SignalExchange"
	ControlPlane_StreamServiceRegistry_FullMethodName   = "/awgmesh.control_plane.v1.ControlPlane/StreamServiceRegistry"
	ControlPlane_QueryAudit_FullMethodName              = "/awgmesh.control_plane.v1.ControlPlane/QueryAudit"
	ControlPlane_DecommissionNode_FullMethodName        = "/awgmesh.control_plane.v1.ControlPlane/DecommissionNode"
	ControlPlane_StreamCertUpdate_FullMethodName        = "/awgmesh.control_plane.v1.ControlPlane/StreamCertUpdate"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// F-009 control plane gRPC service.
//
// Mesh-internal nodes (master, egress, ingress, balancer) and clients connect
// to a long-running mesh-ctl daemon implementing this service. The daemon
// holds the authoritative state of the mesh:
//   - identity registry (which nodes exist + their certs + roles)
//   - ownership ledger (which master owns which overlay /32)
//   - rotation orchestration (mesh-wide AWG param swap)
//   - NAT-traversal signal exchange
//   - service registry distribution to ingress nodes
//   - audit log query
//
// Streaming RPCs push updates as they happen — clientd does not poll. mTLS +
// node certificates authenticate every call (FR-16 cert lifecycle).
type ControlPlaneClient interface {
	// Node lifecycle.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// Streaming peer-list distribution. Client sends one StreamPeerListRequest
	// and the server pushes PeerListUpdate messages as the mesh evolves.
	StreamPeerList(ctx context.Context, in *StreamPeerListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerListUpdate], error)
	// Streaming ownership-ledger distribution. Drives clientd AllowedIPs
	// partitions per FR-5 HA-2.
	StreamOwnership(ctx context.Context, in *StreamOwnershipRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OwnershipUpdate], error)
	// Mesh-wide rotation orchestration (FR-8). Client streams ack messages
	// back so the control plane can roll back on partial-apply.
	RotateAWGParamsMeshWide(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RotateRequest, RotateResponse], error)
	// NAT-traversal signal exchange. Bidirectional stream — both ends relay
	// ICE candidates through the control plane (analogue of Tailscale DERP).
	SignalExchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalRequest, SignalResponse], error)
	// Streaming service registry — ingress nodes receive hostname-to-target
	// bindings.
	StreamServiceRegistry(ctx context.Context, in *StreamServiceRegistryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceRegistryUpdate], error)
	// Audit log query (FR-20). Operator-facing.
	QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEntry], error)
	// Decommissioning (FR-15). Operator initiates, control plane orchestrates
	// ownership reassignment + peer removal.
	DecommissionNode(ctx context.Context, in *DecommissionRequest, opts ...grpc.CallOption) (*DecommissionResponse, error)
	// Cert distribution (FR-16). New cert pushed when 7-day overlap window opens.
	StreamCertUpdate(ctx context.Context, in *StreamCertRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CertUpdate], error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *controlPlaneClient) StreamPeerList(ctx context.Context, in *StreamPeerListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerListUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[1], ControlPlane_StreamPeerList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPeerListRequest, PeerListUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamPeerListClient = grpc.ServerStreamingClient[PeerListUpdate]

func (c *controlPlaneClient) StreamOwnership(ctx context.Context, in *StreamOwnershipRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OwnershipUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[2], ControlPlane_StreamOwnership_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamOwnershipRequest, OwnershipUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamOwnershipClient = grpc.ServerStreamingClient[OwnershipUpdate]

func (c *controlPlaneClient) RotateAWGParamsMeshWide(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RotateRequest, RotateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[3], ControlPlane_RotateAWGParamsMeshWide_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RotateRequest, RotateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_RotateAWGParamsMeshWideClient = grpc.BidiStreamingClient[RotateRequest, RotateResponse]

func (c *controlPlaneClient) SignalExchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalRequest, SignalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[4], ControlPlane_SignalExchange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignalRequest, SignalResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_SignalExchangeClient = grpc.BidiStreamingClient[SignalRequest, SignalResponse]

func (c *controlPlaneClient) StreamServiceRegistry(ctx context.Context, in *StreamServiceRegistryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceRegistryUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[5], ControlPlane_StreamServiceRegistry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamServiceRegistryRequest, ServiceRegistryUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamServiceRegistryClient = grpc.ServerStreamingClient[ServiceRegistryUpdate]

func (c *controlPlaneClient) QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[6], ControlPlane_QueryAudit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryAuditRequest, AuditEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_QueryAuditClient = grpc.ServerStreamingClient[AuditEntry]

func (c *controlPlaneClient) DecommissionNode(ctx context.Context, in *DecommissionRequest, opts ...grpc.CallOption) (*DecommissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecommissionResponse)
	err := c.cc.Invoke(ctx, ControlPlane_DecommissionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StreamCertUpdate(ctx context.Context, in *StreamCertRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CertUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[7], ControlPlane_StreamCertUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCertRequest, CertUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamCertUpdateClient = grpc.ServerStreamingClient[CertUpdate]

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// F-009 control plane gRPC service.
//
// Mesh-internal nodes (master, egress, ingress, balancer) and clients connect
// to a long-running mesh-ctl daemon implementing this service. The daemon
// holds the authoritative state of the mesh:
//   - identity registry (which nodes exist + their certs + roles)
//   - ownership ledger (which master owns which overlay /32)
//   - rotation orchestration (mesh-wide AWG param swap)
//   - NAT-traversal signal exchange
//   - service registry distribution to ingress nodes
//   - audit log query
//
// Streaming RPCs push updates as they happen — clientd does not poll. mTLS +
// node certificates authenticate every call (FR-16 cert lifecycle).
type ControlPlaneServer interface {
	// Node lifecycle.
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// Streaming peer-list distribution. Client sends one StreamPeerListRequest
	// and the server pushes PeerListUpdate messages as the mesh evolves.
	StreamPeerList(*StreamPeerListRequest, grpc.ServerStreamingServer[PeerListUpdate]) error
	// Streaming ownership-ledger distribution. Drives clientd AllowedIPs
	// partitions per FR-5 HA-2.
	StreamOwnership(*StreamOwnershipRequest, grpc.ServerStreamingServer[OwnershipUpdate]) error
	// Mesh-wide rotation orchestration (FR-8). Client streams ack messages
	// back so the control plane can roll back on partial-apply.
	RotateAWGParamsMeshWide(grpc.BidiStreamingServer[RotateRequest, RotateResponse]) error
	// NAT-traversal signal exchange. Bidirectional stream — both ends relay
	// ICE candidates through the control plane (analogue of Tailscale DERP).
	SignalExchange(grpc.BidiStreamingServer[SignalRequest, SignalResponse]) error
	// Streaming service registry — ingress nodes receive hostname-to-target
	// bindings.
	StreamServiceRegistry(*StreamServiceRegistryRequest, grpc.ServerStreamingServer[ServiceRegistryUpdate]) error
	// Audit log query (FR-20). Operator-facing.
	QueryAudit(*QueryAuditRequest, grpc.ServerStreamingServer[AuditEntry]) error
	// Decommissioning (FR-15). Operator initiates, control plane orchestrates
	// ownership reassignment + peer removal.
	DecommissionNode(context.Context, *DecommissionRequest) (*DecommissionResponse, error)
	// Cert distribution (FR-16). New cert pushed when 7-day overlap window opens.
	StreamCertUpdate(*StreamCertRequest, grpc.ServerStreamingServer[CertUpdate]) error
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) StreamPeerList(*StreamPeerListRequest, grpc.ServerStreamingServer[PeerListUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamPeerList not implemented")
}
func (UnimplementedControlPlaneServer) StreamOwnership(*StreamOwnershipRequest, grpc.ServerStreamingServer[OwnershipUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamOwnership not implemented")
}
func (UnimplementedControlPlaneServer) RotateAWGParamsMeshWide(grpc.BidiStreamingServer[RotateRequest, RotateResponse]) error {
	return status.Error(codes.Unimplemented, "method RotateAWGParamsMeshWide not implemented")
}
func (UnimplementedControlPlaneServer) SignalExchange(grpc.BidiStreamingServer[SignalRequest, SignalResponse]) error {
	return status.Error(codes.Unimplemented, "method SignalExchange not implemented")
}
func (UnimplementedControlPlaneServer) StreamServiceRegistry(*StreamServiceRegistryRequest, grpc.ServerStreamingServer[ServiceRegistryUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamServiceRegistry not implemented")
}
func (UnimplementedControlPlaneServer) QueryAudit(*QueryAuditRequest, grpc.ServerStreamingServer[AuditEntry]) error {
	return status.Error(codes.Unimplemented, "method QueryAudit not implemented")
}
func (UnimplementedControlPlaneServer) DecommissionNode(context.Context, *DecommissionRequest) (*DecommissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecommissionNode not implemented")
}
func (UnimplementedControlPlaneServer) StreamCertUpdate(*StreamCertRequest, grpc.ServerStreamingServer[CertUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamCertUpdate not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _ControlPlane_StreamPeerList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPeerListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamPeerList(m, &grpc.GenericServerStream[StreamPeerListRequest, PeerListUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamPeerListServer = grpc.ServerStreamingServer[PeerListUpdate]

func _ControlPlane_StreamOwnership_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOwnershipRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamOwnership(m, &grpc.GenericServerStream[StreamOwnershipRequest, OwnershipUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamOwnershipServer = grpc.ServerStreamingServer[OwnershipUpdate]

func _ControlPlane_RotateAWGParamsMeshWide_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).RotateAWGParamsMeshWide(&grpc.GenericServerStream[RotateRequest, RotateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_RotateAWGParamsMeshWideServer = grpc.BidiStreamingServer[RotateRequest, RotateResponse]

func _ControlPlane_SignalExchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).SignalExchange(&grpc.GenericServerStream[SignalRequest, SignalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_SignalExchangeServer = grpc.BidiStreamingServer[SignalRequest, SignalResponse]

func _ControlPlane_StreamServiceRegistry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamServiceRegistryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamServiceRegistry(m, &grpc.GenericServerStream[StreamServiceRegistryRequest, ServiceRegistryUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamServiceRegistryServer = grpc.ServerStreamingServer[ServiceRegistryUpdate]

func _ControlPlane_QueryAudit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryAuditRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).QueryAudit(m, &grpc.GenericServerStream[QueryAuditRequest, AuditEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_QueryAuditServer = grpc.ServerStreamingServer[AuditEntry]

func _ControlPlane_DecommissionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).DecommissionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_DecommissionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).DecommissionNode(ctx, req.(*DecommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StreamCertUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCertRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamCertUpdate(m, &grpc.GenericServerStream[StreamCertRequest, CertUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamCertUpdateServer = grpc.ServerStreamingServer[CertUpdate]

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "awgmesh.control_plane.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _ControlPlane_RegisterNode_Handler,
		},
		{
			MethodName: "DecommissionNode",
			Handler:    _ControlPlane_DecommissionNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _ControlPlane_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamPeerList",
			Handler:       _ControlPlane_StreamPeerList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOwnership",
			Handler:       _ControlPlane_StreamOwnership_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RotateAWGParamsMeshWide",
			Handler:       _ControlPlane_RotateAWGParamsMeshWide_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SignalExchange",
			Handler:       _ControlPlane_SignalExchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamServiceRegistry",
			Handler:       _ControlPlane_StreamServiceRegistry_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryAudit",
			Handler:       _ControlPlane_QueryAudit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCertUpdate",
			Handler:       _ControlPlane_StreamCertUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control_plane.proto",
}
