package cmd

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/coonfuuseed-paandaa/awg-mesh/pkg/mikrotik"
	"github.com/coonfuuseed-paandaa/awg-mesh/pkg/topology"
	"github.com/spf13/cobra"
)

func newRoutingCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "routing",
		Short: "Manage routing configuration",
	}

	cmd.AddCommand(newRoutingGenerateCommand())
	return cmd
}

func newRoutingGenerateCommand() *cobra.Command {
	var platform string
	var clientName string
	var gateway string

	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate router config from topology routing policies",
		Long:  "Generate platform-specific routing configuration (MikroTik .rsc, Linux .sh, or generic JSON) from topology routing_policies.",
		RunE: func(cmd *cobra.Command, args []string) error {
			topo, err := topology.LoadTopology(topologyPath)
			if err != nil {
				return fmt.Errorf("load topology %q: %w", topologyPath, err)
			}

			if clientName == "" {
				if len(topo.Clients) == 0 {
					return fmt.Errorf("no clients in topology")
				}
				clientName = topo.Clients[0].Name
			}

			client := topo.FindClient(clientName)
			if client == nil {
				return fmt.Errorf("client %q not found in topology", clientName)
			}

			if len(client.RoutingPolicies) == 0 {
				return fmt.Errorf("client %q has no routing_policies", clientName)
			}

			// B13 fix: default --gateway to first master overlay IP, not client self-IP.
			// Using the client's own overlay IP as gateway creates a circular route.
			trimmedGateway := strings.TrimSpace(gateway)
			if trimmedGateway == "" {
				if len(client.Masters) > 0 {
					if m := topo.FindMaster(client.Masters[0]); m != nil {
						trimmedGateway = m.OverlayIP
					}
				}
				// Last resort: fall back to client overlay IP (caller can override via --gateway).
				if trimmedGateway == "" {
					trimmedGateway = client.OverlayIP
				}
			}

			switch strings.ToLower(strings.TrimSpace(platform)) {
			case "mikrotik":
				return generateMikrotik(*client, trimmedGateway, topo)
			case "linux":
				return generateLinux(*client, trimmedGateway, topo)
			case "generic", "json":
				return generateGeneric(topo, *client, trimmedGateway)
			default:
				return fmt.Errorf("unsupported platform %q (supported: mikrotik, linux, generic)", platform)
			}
		},
	}

	cmd.Flags().StringVar(&platform, "platform", "mikrotik", "Target platform (mikrotik, linux, generic)")
	cmd.Flags().StringVar(&clientName, "client", "", "Client name (defaults to first client)")
	cmd.Flags().StringVar(&gateway, "gateway", "", "Gateway IP (defaults to first master overlay IP; last resort: client overlay IP)")

	return cmd
}

func generateMikrotik(client topology.ClientNode, fallbackGateway string, topo *topology.Topology) error {
	// B11 fix: pass topo so each policy routes to its target endpoint's overlay IP.
	script, err := mikrotik.GenerateRoutingRSC(client, fallbackGateway, topo)
	if err != nil {
		return err
	}
	fmt.Print(script)
	return nil
}

func generateLinux(client topology.ClientNode, fallbackGateway string, topo *topology.Topology) error {
	var sb strings.Builder
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# awg-mesh DSCP routing configuration\n")
	sb.WriteString("# Generated by mesh-ctl routing generate --platform linux\n")
	fmt.Fprintf(&sb, "# Client: %s\n\n", client.Name)
	sb.WriteString("set -euo pipefail\n\n")

	for _, policy := range client.RoutingPolicies {
		if err := topology.ValidateDSCP(policy.DSCP); err != nil {
			return fmt.Errorf("client %q policy %q: %w", client.Name, policy.Name, err)
		}
		tableID := 100 + policy.DSCP

		// B12 fix: resolve per-policy gateway from topology targets.
		// Each DSCP class routes to its specific target endpoint, not a single shared gateway.
		gateway, targetName := resolveLinuxGateway(policy, fallbackGateway, topo)

		fmt.Fprintf(&sb, "# Policy: %s (DSCP %d, target: %s)\n", policy.Name, policy.DSCP, targetName)
		fmt.Fprintf(&sb, "iptables -t mangle -A PREROUTING -m connmark --mark %d -j DSCP --set-dscp %d\n", policy.DSCP, policy.DSCP)
		fmt.Fprintf(&sb, "ip rule add fwmark %d lookup %d 2>/dev/null || true\n", policy.DSCP, tableID)
		fmt.Fprintf(&sb, "ip route replace default via %s table %d\n\n", gateway, tableID)
	}

	fmt.Print(sb.String())
	return nil
}

// resolveLinuxGateway resolves the per-policy gateway for linux iproute2 output.
// Mirrors the logic in pkg/mikrotik/routing.go::resolveTargetGateway.
func resolveLinuxGateway(policy topology.RoutingPolicy, fallback string, topo *topology.Topology) (gateway, targetName string) {
	if topo != nil && len(policy.Targets) > 0 {
		name := policy.Targets[0]
		if ep := topo.FindEndpoint(name); ep != nil && strings.TrimSpace(ep.OverlayIP) != "" {
			return ep.OverlayIP, name
		}
		if m := topo.FindMaster(name); m != nil && strings.TrimSpace(m.OverlayIP) != "" {
			return m.OverlayIP, name
		}
		// Target declared but not found in topology — warn via comment, use fallback.
		targetName = name + " (unresolved)"
	} else {
		targetName = "fallback"
	}
	return fallback, targetName
}

// RoutingJSON represents the generic JSON output for routing configuration.
type RoutingJSON struct {
	Gateway        string          `json:"gateway"`
	DSCPMap        []DSCPMapEntry  `json:"dscp_map"`
	FallbackRoutes []FallbackRoute `json:"fallback_routes,omitempty"`
}

// DSCPMapEntry represents a single DSCP mapping entry.
type DSCPMapEntry struct {
	DSCP    int      `json:"dscp"`
	Name    string   `json:"name"`
	Targets []string `json:"targets"`
	// Gateway is the resolved target overlay IP (empty if unresolvable).
	Gateway string `json:"gateway,omitempty"`
}

// FallbackRoute represents a per-overlay-IP static route for routers without DSCP support.
type FallbackRoute struct {
	OverlayIP string `json:"overlay_ip"`
	NodeName  string `json:"node_name"`
	Via       string `json:"via"`
}

func generateGeneric(topo *topology.Topology, client topology.ClientNode, fallbackGateway string) error {
	entries := make([]DSCPMapEntry, 0, len(client.RoutingPolicies))
	for _, policy := range client.RoutingPolicies {
		targets := make([]string, len(policy.Targets))
		copy(targets, policy.Targets)
		// Resolve per-policy gateway for generic output.
		gw, _ := resolveLinuxGateway(policy, fallbackGateway, topo)
		entries = append(entries, DSCPMapEntry{
			DSCP:    policy.DSCP,
			Name:    policy.Name,
			Targets: targets,
			Gateway: gw,
		})
	}

	// Build fallback overlay-IP routes for routers without DSCP support
	fallback := make([]FallbackRoute, 0)
	for _, ep := range topo.Endpoints {
		if strings.TrimSpace(ep.OverlayIP) != "" {
			fallback = append(fallback, FallbackRoute{
				OverlayIP: ep.OverlayIP,
				NodeName:  ep.Name,
				Via:       fallbackGateway,
			})
		}
	}
	for _, m := range topo.Masters {
		if m.Exit && strings.TrimSpace(m.OverlayIP) != "" {
			fallback = append(fallback, FallbackRoute{
				OverlayIP: m.OverlayIP,
				NodeName:  m.Name,
				Via:       fallbackGateway,
			})
		}
	}

	output := RoutingJSON{
		Gateway:        fallbackGateway,
		DSCPMap:        entries,
		FallbackRoutes: fallback,
	}

	data, err := json.MarshalIndent(output, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal JSON: %w", err)
	}
	fmt.Println(string(data))
	return nil
}
