package cmd

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/coonfuuseed-paandaa/awg-mesh/pkg/mikrotik"
	"github.com/coonfuuseed-paandaa/awg-mesh/pkg/topology"
)

func newRoutingCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "routing",
		Short: "Manage routing configuration",
	}

	cmd.AddCommand(newRoutingGenerateCommand())
	return cmd
}

func newRoutingGenerateCommand() *cobra.Command {
	var platform string
	var clientName string
	var gateway string

	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate router config from topology routing policies",
		Long:  "Generate platform-specific routing configuration (MikroTik .rsc, Linux .sh, or generic JSON) from topology routing_policies.",
		RunE: func(cmd *cobra.Command, args []string) error {
			topo, err := topology.LoadTopology(topologyPath)
			if err != nil {
				return fmt.Errorf("load topology %q: %w", topologyPath, err)
			}

			if clientName == "" {
				if len(topo.Clients) == 0 {
					return fmt.Errorf("no clients in topology")
				}
				clientName = topo.Clients[0].Name
			}

			client := topo.FindClient(clientName)
			if client == nil {
				return fmt.Errorf("client %q not found in topology", clientName)
			}

			if len(client.RoutingPolicies) == 0 {
				return fmt.Errorf("client %q has no routing_policies", clientName)
			}

			trimmedGateway := strings.TrimSpace(gateway)
			if trimmedGateway == "" {
				trimmedGateway = client.OverlayIP
			}

			switch strings.ToLower(strings.TrimSpace(platform)) {
			case "mikrotik":
				return generateMikrotik(*client, trimmedGateway)
			case "linux":
				return generateLinux(*client, trimmedGateway)
			case "generic", "json":
				return generateGeneric(topo, *client, trimmedGateway)
			default:
				return fmt.Errorf("unsupported platform %q (supported: mikrotik, linux, generic)", platform)
			}
		},
	}

	cmd.Flags().StringVar(&platform, "platform", "mikrotik", "Target platform (mikrotik, linux, generic)")
	cmd.Flags().StringVar(&clientName, "client", "", "Client name (defaults to first client)")
	cmd.Flags().StringVar(&gateway, "gateway", "", "Gateway IP (defaults to client overlay IP)")

	return cmd
}

func generateMikrotik(client topology.ClientNode, gateway string) error {
	script, err := mikrotik.GenerateRoutingRSC(client, gateway)
	if err != nil {
		return err
	}
	fmt.Print(script)
	return nil
}

func generateLinux(client topology.ClientNode, gateway string) error {
	var sb strings.Builder
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# awg-mesh DSCP routing configuration\n")
	sb.WriteString("# Generated by mesh-ctl routing generate --platform linux\n")
	fmt.Fprintf(&sb, "# Client: %s\n\n", client.Name)
	sb.WriteString("set -euo pipefail\n\n")

	for _, policy := range client.RoutingPolicies {
		tableID := 100 + policy.DSCP
		fmt.Fprintf(&sb, "# Policy: %s (DSCP %d)\n", policy.Name, policy.DSCP)
		fmt.Fprintf(&sb, "iptables -t mangle -A PREROUTING -m connmark --mark %d -j DSCP --set-dscp %d\n", policy.DSCP, policy.DSCP)
		fmt.Fprintf(&sb, "ip rule add fwmark %d lookup %d 2>/dev/null || true\n", policy.DSCP, tableID)
		fmt.Fprintf(&sb, "ip route replace default via %s table %d\n\n", gateway, tableID)
	}

	fmt.Print(sb.String())
	return nil
}

// RoutingJSON represents the generic JSON output for routing configuration.
type RoutingJSON struct {
	Gateway        string           `json:"gateway"`
	DSCPMap        []DSCPMapEntry   `json:"dscp_map"`
	FallbackRoutes []FallbackRoute  `json:"fallback_routes,omitempty"`
}

// DSCPMapEntry represents a single DSCP mapping entry.
type DSCPMapEntry struct {
	DSCP    int      `json:"dscp"`
	Name    string   `json:"name"`
	Targets []string `json:"targets"`
}

// FallbackRoute represents a per-overlay-IP static route for routers without DSCP support.
type FallbackRoute struct {
	OverlayIP string `json:"overlay_ip"`
	NodeName  string `json:"node_name"`
	Via       string `json:"via"`
}

func generateGeneric(topo *topology.Topology, client topology.ClientNode, gateway string) error {
	entries := make([]DSCPMapEntry, 0, len(client.RoutingPolicies))
	for _, policy := range client.RoutingPolicies {
		targets := make([]string, len(policy.Targets))
		copy(targets, policy.Targets)
		entries = append(entries, DSCPMapEntry{
			DSCP:    policy.DSCP,
			Name:    policy.Name,
			Targets: targets,
		})
	}

	// Build fallback overlay-IP routes for routers without DSCP support
	fallback := make([]FallbackRoute, 0)
	for _, ep := range topo.Endpoints {
		if strings.TrimSpace(ep.OverlayIP) != "" {
			fallback = append(fallback, FallbackRoute{
				OverlayIP: ep.OverlayIP,
				NodeName:  ep.Name,
				Via:       gateway,
			})
		}
	}
	for _, m := range topo.Masters {
		if m.Exit && strings.TrimSpace(m.OverlayIP) != "" {
			fallback = append(fallback, FallbackRoute{
				OverlayIP: m.OverlayIP,
				NodeName:  m.Name,
				Via:       gateway,
			})
		}
	}

	output := RoutingJSON{
		Gateway:        gateway,
		DSCPMap:        entries,
		FallbackRoutes: fallback,
	}

	data, err := json.MarshalIndent(output, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal JSON: %w", err)
	}
	fmt.Println(string(data))
	return nil
}
