package mikrotik

import (
	"fmt"
	"strings"

	"github.com/coonfuuseed-paandaa/awg-mesh/pkg/topology"
)

// routingScriptTemplate generates per-DSCP routing tables on MikroTik.
// Each routing_policy in the client config gets its own routing table,
// /routing/rule entry, and default route pointing to the policy's target
// endpoint overlay IP (B11 fix: was a single shared table with client self-IP
// as the gateway, making DSCP routing a silent no-op).
const routingScriptTemplate = `# awg-mesh DSCP routing configuration
# Generated by mesh-ctl routing generate --platform mikrotik
# Client: {{.ClientName}}
#
# IMPORTANT — Classifier rules required.
#
# This script installs per-DSCP routing tables and /routing/rule entries that
# steer marked connections to the correct VPN endpoint. However, it does NOT
# tag any traffic by itself. You must add mark-connection rules upstream so
# each connection gets the correct connection-mark before the routing rules run.
# See the commented starter block at the bottom of this file for ready-to-edit
# examples.
#
# Without classifier rules, DSCP routing is a no-op — no packet is
# routed through the VPN.

{{- range .Policies}}
/routing/table
add name={{.TableName}} fib comment="awg-mesh: {{.Name}} (DSCP {{.DSCP}})"

/ip/firewall/mangle
add chain=prerouting connection-mark={{.ConnectionMark}} action=change-dscp new-dscp={{.DSCP}} comment="awg-mesh: {{.Name}}"

/routing/rule
add fwmark={{.DSCP}} table={{.TableName}} comment="awg-mesh: route DSCP {{.DSCP}} via {{.TableName}}"

/ip/route
add dst-address=0.0.0.0/0 gateway={{.Gateway}} routing-table={{.TableName}} distance=5 comment="awg-mesh: {{.Name}} default via {{.Target}}"
{{end}}
# -----------------------------------------------------------------------
# CLASSIFIER TEMPLATE (uncomment and edit to activate DSCP routing).
#
# Each policy below has a matching commented block. Pick at least one
# mark-connection rule per policy and fill in the match criteria
# (src/dst address, address-list, interface, port, etc.).
# -----------------------------------------------------------------------
{{- range .Policies}}
#
# Policy: {{.Name}} (DSCP {{.DSCP}}, table {{.TableName}}, target {{.Target}} gateway {{.Gateway}})
# Example — route traffic to an address list through this VPN:
#   /ip/firewall/address-list
#   add list={{.Name}}-dst address=1.2.3.0/24 comment="awg-mesh: {{.Name}} — sample"
#
#   /ip/firewall/mangle
#   add chain=prerouting dst-address-list={{.Name}}-dst action=mark-connection \
#     new-connection-mark={{.ConnectionMark}} passthrough=yes \
#     comment="awg-mesh: classify {{.Name}}"
{{- end}}
`

// policyEntry holds per-policy data for the MikroTik routing template.
type policyEntry struct {
	Name           string
	TableName      string // e.g. "vpn-mesh-10"
	ConnectionMark string // e.g. "vpn-asia-conn"
	DSCP           int
	Gateway        string // resolved target overlay IP
	Target         string // target node name (for comments)
}

// RoutingScriptData holds data for generating a MikroTik routing .rsc script.
type RoutingScriptData struct {
	ClientName string
	Policies   []policyEntry
}

// GenerateRoutingRSC generates a MikroTik .rsc script for DSCP-based routing.
// Each routing_policy in client.RoutingPolicies gets its own routing table
// (vpn-mesh-<dscp>), /routing/rule, and a default route to the policy's target
// endpoint overlay IP resolved from topo.
//
// fallbackGateway is used when a policy's target cannot be resolved from topo.
// If fallbackGateway is empty and topo is nil, returns an error.
func GenerateRoutingRSC(client topology.ClientNode, fallbackGateway string, topo *topology.Topology) (string, error) {
	if len(client.RoutingPolicies) == 0 {
		return "", fmt.Errorf("client %q has no routing policies", client.Name)
	}

	entries := make([]policyEntry, 0, len(client.RoutingPolicies))
	for _, policy := range client.RoutingPolicies {
		if err := topology.ValidateDSCP(policy.DSCP); err != nil {
			return "", fmt.Errorf("routing policy %q: %w", policy.Name, err)
		}

		gateway, targetName := resolveTargetGateway(policy, fallbackGateway, topo)
		if gateway == "" {
			return "", fmt.Errorf("routing policy %q: cannot determine gateway — no targets and no fallback gateway provided", policy.Name)
		}

		entries = append(entries, policyEntry{
			Name:           policy.Name,
			TableName:      fmt.Sprintf("vpn-mesh-%d", policy.DSCP),
			ConnectionMark: policy.Name + "-conn",
			DSCP:           policy.DSCP,
			Gateway:        gateway,
			Target:         targetName,
		})
	}

	data := RoutingScriptData{
		ClientName: client.Name,
		Policies:   entries,
	}

	script, err := executeTemplate("routing-rsc", routingScriptTemplate, data)
	if err != nil {
		return "", fmt.Errorf("render routing script: %w", err)
	}
	return script, nil
}

// resolveTargetGateway resolves the gateway IP for a routing policy.
// It looks up the first target in the policy against the topology:
//   - If the target is an endpoint, its OverlayIP is used.
//   - If the target is a master with exit=true, its OverlayIP is used.
//
// Falls back to fallbackGateway if topo is nil or the target is not found.
// Returns (gateway, targetName) — targetName is the resolved node name or
// "unknown" if falling back.
func resolveTargetGateway(policy topology.RoutingPolicy, fallback string, topo *topology.Topology) (string, string) {
	if topo != nil && len(policy.Targets) > 0 {
		targetName := policy.Targets[0]
		// Try endpoint first.
		if ep := topo.FindEndpoint(targetName); ep != nil && strings.TrimSpace(ep.OverlayIP) != "" {
			return ep.OverlayIP, targetName
		}
		// Try master (exit nodes only).
		if m := topo.FindMaster(targetName); m != nil && strings.TrimSpace(m.OverlayIP) != "" {
			return m.OverlayIP, targetName
		}
	}
	// Fall back to the explicitly provided gateway.
	if fallback != "" {
		return fallback, "fallback"
	}
	return "", ""
}
