package mikrotik

import (
	"fmt"
	"strings"

	"github.com/thebtf/awg-mesh/pkg/topology"
)

const routingScriptTemplate = `# awg-mesh DSCP routing configuration
# Generated by mesh-ctl routing generate --platform mikrotik
# Client: {{.ClientName}}

/routing/table
add name=vpn-mesh fib comment="awg-mesh: VPN routing table"

/ip/firewall/mangle
{{- range .MangleRules }}
add chain=prerouting connection-mark={{.ConnectionMark}} action=change-dscp new-dscp={{.DSCP}} comment="awg-mesh: {{.Name}}"
{{- end }}

/ip/route
add dst-address=0.0.0.0/0 gateway={{.Gateway}} routing-table=vpn-mesh distance=5 comment="awg-mesh: default VPN route"
`

// MangleRule represents a single mangle rule for DSCP marking.
type MangleRule struct {
	Name           string
	ConnectionMark string
	DSCP           int
}

// RoutingScriptData holds data for generating a MikroTik routing .rsc script.
type RoutingScriptData struct {
	ClientName  string
	Gateway     string
	MangleRules []MangleRule
}

// GenerateRoutingRSC generates a MikroTik .rsc script for DSCP-based routing.
func GenerateRoutingRSC(client topology.ClientNode, gateway string) (string, error) {
	trimmedGateway := strings.TrimSpace(gateway)
	if trimmedGateway == "" {
		return "", fmt.Errorf("gateway address is required")
	}
	if len(client.RoutingPolicies) == 0 {
		return "", fmt.Errorf("client %q has no routing policies", client.Name)
	}

	rules := make([]MangleRule, 0, len(client.RoutingPolicies))
	for _, policy := range client.RoutingPolicies {
		if policy.DSCP < 1 || policy.DSCP > 63 {
			return "", fmt.Errorf("routing policy %q: DSCP value %d out of range (1-63)", policy.Name, policy.DSCP)
		}
		rules = append(rules, MangleRule{
			Name:           policy.Name,
			ConnectionMark: policy.Name + "-conn",
			DSCP:           policy.DSCP,
		})
	}

	data := RoutingScriptData{
		ClientName:  client.Name,
		Gateway:     trimmedGateway,
		MangleRules: rules,
	}

	script, err := executeTemplate("routing-rsc", routingScriptTemplate, data)
	if err != nil {
		return "", fmt.Errorf("render routing script: %w", err)
	}
	return script, nil
}
