package mikrotik

import (
	"fmt"
	"strings"

	"github.com/coonfuuseed-paandaa/awg-mesh/pkg/topology"
)

const routingScriptTemplate = `# awg-mesh DSCP routing configuration
# Generated by mesh-ctl routing generate --platform mikrotik
# Client: {{.ClientName}}
#
# IMPORTANT — Classifier rules required.
#
# This script installs the DSCP-to-VPN plumbing, but it does NOT tag any
# traffic by itself. You must add mark-connection rules upstream so the
# change-dscp rules below have something to match. See the commented
# starter block at the bottom of this file for ready-to-edit examples.
#
# Without classifier rules, DSCP routing is a no-op — no packet is
# routed through the VPN.

/routing/table
add name=vpn-mesh fib comment="awg-mesh: VPN routing table"

/ip/firewall/mangle
{{- range .MangleRules }}
add chain=prerouting connection-mark={{.ConnectionMark}} action=change-dscp new-dscp={{.DSCP}} comment="awg-mesh: {{.Name}}"
{{- end }}

/ip/route
add dst-address=0.0.0.0/0 gateway={{.Gateway}} routing-table=vpn-mesh distance=5 comment="awg-mesh: default VPN route"

# -----------------------------------------------------------------------
# CLASSIFIER TEMPLATE (uncomment and edit to activate DSCP routing).
#
# Each policy below has a matching commented block. Pick at least one
# mark-connection rule per policy and fill in the match criteria
# (src/dst address, address-list, interface, port, etc.).
# -----------------------------------------------------------------------
{{- range .MangleRules }}
#
# Policy: {{.Name}} (DSCP {{.DSCP}}, connection-mark {{.ConnectionMark}})
# Example — route traffic to an address list through this VPN:
#   /ip/firewall/address-list
#   add list={{.Name}}-dst address=1.2.3.0/24 comment="awg-mesh: {{.Name}} — sample"
#
#   /ip/firewall/mangle
#   add chain=prerouting dst-address-list={{.Name}}-dst action=mark-connection \
#     new-connection-mark={{.ConnectionMark}} passthrough=yes \
#     comment="awg-mesh: classify {{.Name}}"
{{- end }}
`

// MangleRule represents a single mangle rule for DSCP marking.
type MangleRule struct {
	Name           string
	ConnectionMark string
	DSCP           int
}

// RoutingScriptData holds data for generating a MikroTik routing .rsc script.
type RoutingScriptData struct {
	ClientName  string
	Gateway     string
	MangleRules []MangleRule
}

// GenerateRoutingRSC generates a MikroTik .rsc script for DSCP-based routing.
func GenerateRoutingRSC(client topology.ClientNode, gateway string) (string, error) {
	trimmedGateway := strings.TrimSpace(gateway)
	if trimmedGateway == "" {
		return "", fmt.Errorf("gateway address is required")
	}
	if len(client.RoutingPolicies) == 0 {
		return "", fmt.Errorf("client %q has no routing policies", client.Name)
	}

	rules := make([]MangleRule, 0, len(client.RoutingPolicies))
	for _, policy := range client.RoutingPolicies {
		if err := topology.ValidateDSCP(policy.DSCP); err != nil {
			return "", fmt.Errorf("routing policy %q: %w", policy.Name, err)
		}
		rules = append(rules, MangleRule{
			Name:           policy.Name,
			ConnectionMark: policy.Name + "-conn",
			DSCP:           policy.DSCP,
		})
	}

	data := RoutingScriptData{
		ClientName:  client.Name,
		Gateway:     trimmedGateway,
		MangleRules: rules,
	}

	script, err := executeTemplate("routing-rsc", routingScriptTemplate, data)
	if err != nil {
		return "", fmt.Errorf("render routing script: %w", err)
	}
	return script, nil
}
