// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AwgAgent_Init_FullMethodName           = "/awgmesh.AwgAgent/Init"
	AwgAgent_RotateToken_FullMethodName    = "/awgmesh.AwgAgent/RotateToken"
	AwgAgent_AddTunnel_FullMethodName      = "/awgmesh.AwgAgent/AddTunnel"
	AwgAgent_RemoveTunnel_FullMethodName   = "/awgmesh.AwgAgent/RemoveTunnel"
	AwgAgent_ListTunnels_FullMethodName    = "/awgmesh.AwgAgent/ListTunnels"
	AwgAgent_AddPeer_FullMethodName        = "/awgmesh.AwgAgent/AddPeer"
	AwgAgent_RemovePeer_FullMethodName     = "/awgmesh.AwgAgent/RemovePeer"
	AwgAgent_ListPeers_FullMethodName      = "/awgmesh.AwgAgent/ListPeers"
	AwgAgent_RotateParams_FullMethodName   = "/awgmesh.AwgAgent/RotateParams"
	AwgAgent_GetParams_FullMethodName      = "/awgmesh.AwgAgent/GetParams"
	AwgAgent_CaptureRefresh_FullMethodName = "/awgmesh.AwgAgent/CaptureRefresh"
	AwgAgent_GetStatus_FullMethodName      = "/awgmesh.AwgAgent/GetStatus"
	AwgAgent_GetRoutes_FullMethodName      = "/awgmesh.AwgAgent/GetRoutes"
	AwgAgent_GetHealth_FullMethodName      = "/awgmesh.AwgAgent/GetHealth"
)

// AwgAgentClient is the client API for AwgAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AwgAgentClient interface {
	// Onboarding
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	RotateToken(ctx context.Context, in *RotateTokenRequest, opts ...grpc.CallOption) (*RotateTokenResponse, error)
	// Tunnel management (master mode)
	AddTunnel(ctx context.Context, in *AddTunnelRequest, opts ...grpc.CallOption) (*AddTunnelResponse, error)
	RemoveTunnel(ctx context.Context, in *RemoveTunnelRequest, opts ...grpc.CallOption) (*RemoveTunnelResponse, error)
	ListTunnels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TunnelList, error)
	// Peer management (endpoint mode)
	AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error)
	RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error)
	ListPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerList, error)
	// Rotation
	RotateParams(ctx context.Context, in *RotateParamsRequest, opts ...grpc.CallOption) (*RotateParamsResponse, error)
	GetParams(ctx context.Context, in *GetParamsRequest, opts ...grpc.CallOption) (*AwgParams, error)
	// Capture (master only)
	CaptureRefresh(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
	// Status
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error)
	GetRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RouteTable, error)
	GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type awgAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAwgAgentClient(cc grpc.ClientConnInterface) AwgAgentClient {
	return &awgAgentClient{cc}
}

func (c *awgAgentClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, AwgAgent_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) RotateToken(ctx context.Context, in *RotateTokenRequest, opts ...grpc.CallOption) (*RotateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateTokenResponse)
	err := c.cc.Invoke(ctx, AwgAgent_RotateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) AddTunnel(ctx context.Context, in *AddTunnelRequest, opts ...grpc.CallOption) (*AddTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTunnelResponse)
	err := c.cc.Invoke(ctx, AwgAgent_AddTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) RemoveTunnel(ctx context.Context, in *RemoveTunnelRequest, opts ...grpc.CallOption) (*RemoveTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTunnelResponse)
	err := c.cc.Invoke(ctx, AwgAgent_RemoveTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) ListTunnels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TunnelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelList)
	err := c.cc.Invoke(ctx, AwgAgent_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPeerResponse)
	err := c.cc.Invoke(ctx, AwgAgent_AddPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePeerResponse)
	err := c.cc.Invoke(ctx, AwgAgent_RemovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) ListPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerList)
	err := c.cc.Invoke(ctx, AwgAgent_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) RotateParams(ctx context.Context, in *RotateParamsRequest, opts ...grpc.CallOption) (*RotateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateParamsResponse)
	err := c.cc.Invoke(ctx, AwgAgent_RotateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) GetParams(ctx context.Context, in *GetParamsRequest, opts ...grpc.CallOption) (*AwgParams, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AwgParams)
	err := c.cc.Invoke(ctx, AwgAgent_GetParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) CaptureRefresh(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, AwgAgent_CaptureRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, AwgAgent_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) GetRoutes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RouteTable, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteTable)
	err := c.cc.Invoke(ctx, AwgAgent_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awgAgentClient) GetHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AwgAgent_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AwgAgentServer is the server API for AwgAgent service.
// All implementations must embed UnimplementedAwgAgentServer
// for forward compatibility.
type AwgAgentServer interface {
	// Onboarding
	Init(context.Context, *InitRequest) (*InitResponse, error)
	RotateToken(context.Context, *RotateTokenRequest) (*RotateTokenResponse, error)
	// Tunnel management (master mode)
	AddTunnel(context.Context, *AddTunnelRequest) (*AddTunnelResponse, error)
	RemoveTunnel(context.Context, *RemoveTunnelRequest) (*RemoveTunnelResponse, error)
	ListTunnels(context.Context, *Empty) (*TunnelList, error)
	// Peer management (endpoint mode)
	AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error)
	RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error)
	ListPeers(context.Context, *Empty) (*PeerList, error)
	// Rotation
	RotateParams(context.Context, *RotateParamsRequest) (*RotateParamsResponse, error)
	GetParams(context.Context, *GetParamsRequest) (*AwgParams, error)
	// Capture (master only)
	CaptureRefresh(context.Context, *CaptureRequest) (*CaptureResponse, error)
	// Status
	GetStatus(context.Context, *Empty) (*NodeStatus, error)
	GetRoutes(context.Context, *Empty) (*RouteTable, error)
	GetHealth(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedAwgAgentServer()
}

// UnimplementedAwgAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAwgAgentServer struct{}

func (UnimplementedAwgAgentServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedAwgAgentServer) RotateToken(context.Context, *RotateTokenRequest) (*RotateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateToken not implemented")
}
func (UnimplementedAwgAgentServer) AddTunnel(context.Context, *AddTunnelRequest) (*AddTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTunnel not implemented")
}
func (UnimplementedAwgAgentServer) RemoveTunnel(context.Context, *RemoveTunnelRequest) (*RemoveTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTunnel not implemented")
}
func (UnimplementedAwgAgentServer) ListTunnels(context.Context, *Empty) (*TunnelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedAwgAgentServer) AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPeer not implemented")
}
func (UnimplementedAwgAgentServer) RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePeer not implemented")
}
func (UnimplementedAwgAgentServer) ListPeers(context.Context, *Empty) (*PeerList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedAwgAgentServer) RotateParams(context.Context, *RotateParamsRequest) (*RotateParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateParams not implemented")
}
func (UnimplementedAwgAgentServer) GetParams(context.Context, *GetParamsRequest) (*AwgParams, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParams not implemented")
}
func (UnimplementedAwgAgentServer) CaptureRefresh(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureRefresh not implemented")
}
func (UnimplementedAwgAgentServer) GetStatus(context.Context, *Empty) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAwgAgentServer) GetRoutes(context.Context, *Empty) (*RouteTable, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedAwgAgentServer) GetHealth(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedAwgAgentServer) mustEmbedUnimplementedAwgAgentServer() {}
func (UnimplementedAwgAgentServer) testEmbeddedByValue()                  {}

// UnsafeAwgAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AwgAgentServer will
// result in compilation errors.
type UnsafeAwgAgentServer interface {
	mustEmbedUnimplementedAwgAgentServer()
}

func RegisterAwgAgentServer(s grpc.ServiceRegistrar, srv AwgAgentServer) {
	// If the following call panics, it indicates UnimplementedAwgAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AwgAgent_ServiceDesc, srv)
}

func _AwgAgent_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_RotateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).RotateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_RotateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).RotateToken(ctx, req.(*RotateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_AddTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).AddTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_AddTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).AddTunnel(ctx, req.(*AddTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_RemoveTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).RemoveTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_RemoveTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).RemoveTunnel(ctx, req.(*RemoveTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).ListTunnels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_AddPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).AddPeer(ctx, req.(*AddPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_RemovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).RemovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_RemovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).RemovePeer(ctx, req.(*RemovePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).ListPeers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_RotateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).RotateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_RotateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).RotateParams(ctx, req.(*RotateParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_GetParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).GetParams(ctx, req.(*GetParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_CaptureRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).CaptureRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_CaptureRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).CaptureRefresh(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).GetRoutes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AwgAgent_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwgAgentServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AwgAgent_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwgAgentServer).GetHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AwgAgent_ServiceDesc is the grpc.ServiceDesc for AwgAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AwgAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "awgmesh.AwgAgent",
	HandlerType: (*AwgAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _AwgAgent_Init_Handler,
		},
		{
			MethodName: "RotateToken",
			Handler:    _AwgAgent_RotateToken_Handler,
		},
		{
			MethodName: "AddTunnel",
			Handler:    _AwgAgent_AddTunnel_Handler,
		},
		{
			MethodName: "RemoveTunnel",
			Handler:    _AwgAgent_RemoveTunnel_Handler,
		},
		{
			MethodName: "ListTunnels",
			Handler:    _AwgAgent_ListTunnels_Handler,
		},
		{
			MethodName: "AddPeer",
			Handler:    _AwgAgent_AddPeer_Handler,
		},
		{
			MethodName: "RemovePeer",
			Handler:    _AwgAgent_RemovePeer_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _AwgAgent_ListPeers_Handler,
		},
		{
			MethodName: "RotateParams",
			Handler:    _AwgAgent_RotateParams_Handler,
		},
		{
			MethodName: "GetParams",
			Handler:    _AwgAgent_GetParams_Handler,
		},
		{
			MethodName: "CaptureRefresh",
			Handler:    _AwgAgent_CaptureRefresh_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AwgAgent_GetStatus_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _AwgAgent_GetRoutes_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _AwgAgent_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
