// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\aawgmesh\x1a\vtypes.proto2\xda\b\n" +
	"\bAwgAgent\x123\n" +
	"\x04Init\x12\x14.awgmesh.InitRequest\x1a\x15.awgmesh.InitResponse\x12H\n" +
	"\vRotateToken\x12\x1b.awgmesh.RotateTokenRequest\x1a\x1c.awgmesh.RotateTokenResponse\x12B\n" +
	"\tAddTunnel\x12\x19.awgmesh.AddTunnelRequest\x1a\x1a.awgmesh.AddTunnelResponse\x12K\n" +
	"\fRemoveTunnel\x12\x1c.awgmesh.RemoveTunnelRequest\x1a\x1d.awgmesh.RemoveTunnelResponse\x122\n" +
	"\vListTunnels\x12\x0e.awgmesh.Empty\x1a\x13.awgmesh.TunnelList\x12W\n" +
	"\x10UpdateTunnelPeer\x12 .awgmesh.UpdateTunnelPeerRequest\x1a!.awgmesh.UpdateTunnelPeerResponse\x12<\n" +
	"\aAddPeer\x12\x17.awgmesh.AddPeerRequest\x1a\x18.awgmesh.AddPeerResponse\x12E\n" +
	"\n" +
	"RemovePeer\x12\x1a.awgmesh.RemovePeerRequest\x1a\x1b.awgmesh.RemovePeerResponse\x12.\n" +
	"\tListPeers\x12\x0e.awgmesh.Empty\x1a\x11.awgmesh.PeerList\x12K\n" +
	"\fRotateParams\x12\x1c.awgmesh.RotateParamsRequest\x1a\x1d.awgmesh.RotateParamsResponse\x12:\n" +
	"\tGetParams\x12\x19.awgmesh.GetParamsRequest\x1a\x12.awgmesh.AwgParams\x12N\n" +
	"\rRotateKeypair\x12\x1d.awgmesh.RotateKeypairRequest\x1a\x1e.awgmesh.RotateKeypairResponse\x12C\n" +
	"\x0eCaptureRefresh\x12\x17.awgmesh.CaptureRequest\x1a\x18.awgmesh.CaptureResponse\x120\n" +
	"\tGetStatus\x12\x0e.awgmesh.Empty\x1a\x13.awgmesh.NodeStatus\x120\n" +
	"\tGetRoutes\x12\x0e.awgmesh.Empty\x1a\x13.awgmesh.RouteTable\x124\n" +
	"\tGetHealth\x12\x0e.awgmesh.Empty\x1a\x17.awgmesh.HealthResponse\x12D\n" +
	"\x11GetTransportState\x12\x0e.awgmesh.Empty\x1a\x1f.awgmesh.TransportStateResponseB2Z0github.com/coonfuuseed-paandaa/awg-mesh/v2/protob\x06proto3"

var file_agent_proto_goTypes = []any{
	(*InitRequest)(nil),              // 0: awgmesh.InitRequest
	(*RotateTokenRequest)(nil),       // 1: awgmesh.RotateTokenRequest
	(*AddTunnelRequest)(nil),         // 2: awgmesh.AddTunnelRequest
	(*RemoveTunnelRequest)(nil),      // 3: awgmesh.RemoveTunnelRequest
	(*Empty)(nil),                    // 4: awgmesh.Empty
	(*UpdateTunnelPeerRequest)(nil),  // 5: awgmesh.UpdateTunnelPeerRequest
	(*AddPeerRequest)(nil),           // 6: awgmesh.AddPeerRequest
	(*RemovePeerRequest)(nil),        // 7: awgmesh.RemovePeerRequest
	(*RotateParamsRequest)(nil),      // 8: awgmesh.RotateParamsRequest
	(*GetParamsRequest)(nil),         // 9: awgmesh.GetParamsRequest
	(*RotateKeypairRequest)(nil),     // 10: awgmesh.RotateKeypairRequest
	(*CaptureRequest)(nil),           // 11: awgmesh.CaptureRequest
	(*InitResponse)(nil),             // 12: awgmesh.InitResponse
	(*RotateTokenResponse)(nil),      // 13: awgmesh.RotateTokenResponse
	(*AddTunnelResponse)(nil),        // 14: awgmesh.AddTunnelResponse
	(*RemoveTunnelResponse)(nil),     // 15: awgmesh.RemoveTunnelResponse
	(*TunnelList)(nil),               // 16: awgmesh.TunnelList
	(*UpdateTunnelPeerResponse)(nil), // 17: awgmesh.UpdateTunnelPeerResponse
	(*AddPeerResponse)(nil),          // 18: awgmesh.AddPeerResponse
	(*RemovePeerResponse)(nil),       // 19: awgmesh.RemovePeerResponse
	(*PeerList)(nil),                 // 20: awgmesh.PeerList
	(*RotateParamsResponse)(nil),     // 21: awgmesh.RotateParamsResponse
	(*AwgParams)(nil),                // 22: awgmesh.AwgParams
	(*RotateKeypairResponse)(nil),    // 23: awgmesh.RotateKeypairResponse
	(*CaptureResponse)(nil),          // 24: awgmesh.CaptureResponse
	(*NodeStatus)(nil),               // 25: awgmesh.NodeStatus
	(*RouteTable)(nil),               // 26: awgmesh.RouteTable
	(*HealthResponse)(nil),           // 27: awgmesh.HealthResponse
	(*TransportStateResponse)(nil),   // 28: awgmesh.TransportStateResponse
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: awgmesh.AwgAgent.Init:input_type -> awgmesh.InitRequest
	1,  // 1: awgmesh.AwgAgent.RotateToken:input_type -> awgmesh.RotateTokenRequest
	2,  // 2: awgmesh.AwgAgent.AddTunnel:input_type -> awgmesh.AddTunnelRequest
	3,  // 3: awgmesh.AwgAgent.RemoveTunnel:input_type -> awgmesh.RemoveTunnelRequest
	4,  // 4: awgmesh.AwgAgent.ListTunnels:input_type -> awgmesh.Empty
	5,  // 5: awgmesh.AwgAgent.UpdateTunnelPeer:input_type -> awgmesh.UpdateTunnelPeerRequest
	6,  // 6: awgmesh.AwgAgent.AddPeer:input_type -> awgmesh.AddPeerRequest
	7,  // 7: awgmesh.AwgAgent.RemovePeer:input_type -> awgmesh.RemovePeerRequest
	4,  // 8: awgmesh.AwgAgent.ListPeers:input_type -> awgmesh.Empty
	8,  // 9: awgmesh.AwgAgent.RotateParams:input_type -> awgmesh.RotateParamsRequest
	9,  // 10: awgmesh.AwgAgent.GetParams:input_type -> awgmesh.GetParamsRequest
	10, // 11: awgmesh.AwgAgent.RotateKeypair:input_type -> awgmesh.RotateKeypairRequest
	11, // 12: awgmesh.AwgAgent.CaptureRefresh:input_type -> awgmesh.CaptureRequest
	4,  // 13: awgmesh.AwgAgent.GetStatus:input_type -> awgmesh.Empty
	4,  // 14: awgmesh.AwgAgent.GetRoutes:input_type -> awgmesh.Empty
	4,  // 15: awgmesh.AwgAgent.GetHealth:input_type -> awgmesh.Empty
	4,  // 16: awgmesh.AwgAgent.GetTransportState:input_type -> awgmesh.Empty
	12, // 17: awgmesh.AwgAgent.Init:output_type -> awgmesh.InitResponse
	13, // 18: awgmesh.AwgAgent.RotateToken:output_type -> awgmesh.RotateTokenResponse
	14, // 19: awgmesh.AwgAgent.AddTunnel:output_type -> awgmesh.AddTunnelResponse
	15, // 20: awgmesh.AwgAgent.RemoveTunnel:output_type -> awgmesh.RemoveTunnelResponse
	16, // 21: awgmesh.AwgAgent.ListTunnels:output_type -> awgmesh.TunnelList
	17, // 22: awgmesh.AwgAgent.UpdateTunnelPeer:output_type -> awgmesh.UpdateTunnelPeerResponse
	18, // 23: awgmesh.AwgAgent.AddPeer:output_type -> awgmesh.AddPeerResponse
	19, // 24: awgmesh.AwgAgent.RemovePeer:output_type -> awgmesh.RemovePeerResponse
	20, // 25: awgmesh.AwgAgent.ListPeers:output_type -> awgmesh.PeerList
	21, // 26: awgmesh.AwgAgent.RotateParams:output_type -> awgmesh.RotateParamsResponse
	22, // 27: awgmesh.AwgAgent.GetParams:output_type -> awgmesh.AwgParams
	23, // 28: awgmesh.AwgAgent.RotateKeypair:output_type -> awgmesh.RotateKeypairResponse
	24, // 29: awgmesh.AwgAgent.CaptureRefresh:output_type -> awgmesh.CaptureResponse
	25, // 30: awgmesh.AwgAgent.GetStatus:output_type -> awgmesh.NodeStatus
	26, // 31: awgmesh.AwgAgent.GetRoutes:output_type -> awgmesh.RouteTable
	27, // 32: awgmesh.AwgAgent.GetHealth:output_type -> awgmesh.HealthResponse
	28, // 33: awgmesh.AwgAgent.GetTransportState:output_type -> awgmesh.TransportStateResponse
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
