// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

// AWG obfuscation parameters.
type AwgParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jc            int32                  `protobuf:"varint,1,opt,name=jc,proto3" json:"jc,omitempty"`
	Jmin          int32                  `protobuf:"varint,2,opt,name=jmin,proto3" json:"jmin,omitempty"`
	Jmax          int32                  `protobuf:"varint,3,opt,name=jmax,proto3" json:"jmax,omitempty"`
	S1            int32                  `protobuf:"varint,4,opt,name=s1,proto3" json:"s1,omitempty"`
	S2            int32                  `protobuf:"varint,5,opt,name=s2,proto3" json:"s2,omitempty"`
	S3            int32                  `protobuf:"varint,6,opt,name=s3,proto3" json:"s3,omitempty"`
	S4            int32                  `protobuf:"varint,7,opt,name=s4,proto3" json:"s4,omitempty"`
	H1            int32                  `protobuf:"varint,8,opt,name=h1,proto3" json:"h1,omitempty"`
	H2            int32                  `protobuf:"varint,9,opt,name=h2,proto3" json:"h2,omitempty"`
	H3            int32                  `protobuf:"varint,10,opt,name=h3,proto3" json:"h3,omitempty"`
	H4            int32                  `protobuf:"varint,11,opt,name=h4,proto3" json:"h4,omitempty"`
	I1            string                 `protobuf:"bytes,12,opt,name=i1,proto3" json:"i1,omitempty"`
	I2            string                 `protobuf:"bytes,13,opt,name=i2,proto3" json:"i2,omitempty"`
	I3            string                 `protobuf:"bytes,14,opt,name=i3,proto3" json:"i3,omitempty"`
	I4            string                 `protobuf:"bytes,15,opt,name=i4,proto3" json:"i4,omitempty"`
	I5            string                 `protobuf:"bytes,16,opt,name=i5,proto3" json:"i5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwgParams) Reset() {
	*x = AwgParams{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwgParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwgParams) ProtoMessage() {}

func (x *AwgParams) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwgParams.ProtoReflect.Descriptor instead.
func (*AwgParams) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *AwgParams) GetJc() int32 {
	if x != nil {
		return x.Jc
	}
	return 0
}

func (x *AwgParams) GetJmin() int32 {
	if x != nil {
		return x.Jmin
	}
	return 0
}

func (x *AwgParams) GetJmax() int32 {
	if x != nil {
		return x.Jmax
	}
	return 0
}

func (x *AwgParams) GetS1() int32 {
	if x != nil {
		return x.S1
	}
	return 0
}

func (x *AwgParams) GetS2() int32 {
	if x != nil {
		return x.S2
	}
	return 0
}

func (x *AwgParams) GetS3() int32 {
	if x != nil {
		return x.S3
	}
	return 0
}

func (x *AwgParams) GetS4() int32 {
	if x != nil {
		return x.S4
	}
	return 0
}

func (x *AwgParams) GetH1() int32 {
	if x != nil {
		return x.H1
	}
	return 0
}

func (x *AwgParams) GetH2() int32 {
	if x != nil {
		return x.H2
	}
	return 0
}

func (x *AwgParams) GetH3() int32 {
	if x != nil {
		return x.H3
	}
	return 0
}

func (x *AwgParams) GetH4() int32 {
	if x != nil {
		return x.H4
	}
	return 0
}

func (x *AwgParams) GetI1() string {
	if x != nil {
		return x.I1
	}
	return ""
}

func (x *AwgParams) GetI2() string {
	if x != nil {
		return x.I2
	}
	return ""
}

func (x *AwgParams) GetI3() string {
	if x != nil {
		return x.I3
	}
	return ""
}

func (x *AwgParams) GetI4() string {
	if x != nil {
		return x.I4
	}
	return ""
}

func (x *AwgParams) GetI5() string {
	if x != nil {
		return x.I5
	}
	return ""
}

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,3,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	ListenPort    int32                  `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Peers         []*PeerSpec            `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *NodeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *NodeConfig) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *NodeConfig) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NodeConfig) GetPeers() []*PeerSpec {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EndpointHost  string                 `protobuf:"bytes,2,opt,name=endpoint_host,json=endpointHost,proto3" json:"endpoint_host,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,3,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey  []byte                 `protobuf:"bytes,5,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,6,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Params        *AwgParams             `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSpec) Reset() {
	*x = PeerSpec{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSpec) ProtoMessage() {}

func (x *PeerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSpec.ProtoReflect.Descriptor instead.
func (*PeerSpec) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *PeerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerSpec) GetEndpointHost() string {
	if x != nil {
		return x.EndpointHost
	}
	return ""
}

func (x *PeerSpec) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *PeerSpec) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PeerSpec) GetPresharedKey() []byte {
	if x != nil {
		return x.PresharedKey
	}
	return nil
}

func (x *PeerSpec) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerSpec) GetParams() *AwgParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaCert        []byte                 `protobuf:"bytes,1,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	NodeCert      []byte                 `protobuf:"bytes,2,opt,name=node_cert,json=nodeCert,proto3" json:"node_cert,omitempty"`
	NodeKey       []byte                 `protobuf:"bytes,3,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	Config        *NodeConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *InitRequest) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *InitRequest) GetNodeCert() []byte {
	if x != nil {
		return x.NodeCert
	}
	return nil
}

func (x *InitRequest) GetNodeKey() []byte {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *InitRequest) GetConfig() *NodeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodePublicKey []byte                 `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetNodePublicKey() []byte {
	if x != nil {
		return x.NodePublicKey
	}
	return nil
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RotateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewTokenHash  string                 `protobuf:"bytes,1,opt,name=new_token_hash,json=newTokenHash,proto3" json:"new_token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateTokenRequest) Reset() {
	*x = RotateTokenRequest{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTokenRequest) ProtoMessage() {}

func (x *RotateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTokenRequest.ProtoReflect.Descriptor instead.
func (*RotateTokenRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *RotateTokenRequest) GetNewTokenHash() string {
	if x != nil {
		return x.NewTokenHash
	}
	return ""
}

type RotateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateTokenResponse) Reset() {
	*x = RotateTokenResponse{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTokenResponse) ProtoMessage() {}

func (x *RotateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTokenResponse.ProtoReflect.Descriptor instead.
func (*RotateTokenResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *RotateTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddTunnelRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EndpointHost        string                 `protobuf:"bytes,2,opt,name=endpoint_host,json=endpointHost,proto3" json:"endpoint_host,omitempty"`
	OverlayIp           string                 `protobuf:"bytes,3,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	BalancerIp          string                 `protobuf:"bytes,4,opt,name=balancer_ip,json=balancerIp,proto3" json:"balancer_ip,omitempty"`
	PeerPublicKey       []byte                 `protobuf:"bytes,5,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	PresharedKey        []byte                 `protobuf:"bytes,6,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	Params              *AwgParams             `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Weight              int32                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Backup              bool                   `protobuf:"varint,9,opt,name=backup,proto3" json:"backup,omitempty"`
	TransportSubnet     string                 `protobuf:"bytes,10,opt,name=transport_subnet,json=transportSubnet,proto3" json:"transport_subnet,omitempty"`
	MasterTransportIp   string                 `protobuf:"bytes,11,opt,name=master_transport_ip,json=masterTransportIp,proto3" json:"master_transport_ip,omitempty"`
	EndpointTransportIp string                 `protobuf:"bytes,12,opt,name=endpoint_transport_ip,json=endpointTransportIp,proto3" json:"endpoint_transport_ip,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,13,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"` // v1.12.8: admin-source-of-truth AllowedIPs for master-side peer
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AddTunnelRequest) Reset() {
	*x = AddTunnelRequest{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTunnelRequest) ProtoMessage() {}

func (x *AddTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTunnelRequest.ProtoReflect.Descriptor instead.
func (*AddTunnelRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *AddTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTunnelRequest) GetEndpointHost() string {
	if x != nil {
		return x.EndpointHost
	}
	return ""
}

func (x *AddTunnelRequest) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *AddTunnelRequest) GetBalancerIp() string {
	if x != nil {
		return x.BalancerIp
	}
	return ""
}

func (x *AddTunnelRequest) GetPeerPublicKey() []byte {
	if x != nil {
		return x.PeerPublicKey
	}
	return nil
}

func (x *AddTunnelRequest) GetPresharedKey() []byte {
	if x != nil {
		return x.PresharedKey
	}
	return nil
}

func (x *AddTunnelRequest) GetParams() *AwgParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AddTunnelRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AddTunnelRequest) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

func (x *AddTunnelRequest) GetTransportSubnet() string {
	if x != nil {
		return x.TransportSubnet
	}
	return ""
}

func (x *AddTunnelRequest) GetMasterTransportIp() string {
	if x != nil {
		return x.MasterTransportIp
	}
	return ""
}

func (x *AddTunnelRequest) GetEndpointTransportIp() string {
	if x != nil {
		return x.EndpointTransportIp
	}
	return ""
}

func (x *AddTunnelRequest) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

type AddTunnelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MasterPublicKey []byte                 `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	InterfaceName   string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	ListenPort      int32                  `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddTunnelResponse) Reset() {
	*x = AddTunnelResponse{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTunnelResponse) ProtoMessage() {}

func (x *AddTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTunnelResponse.ProtoReflect.Descriptor instead.
func (*AddTunnelResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *AddTunnelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddTunnelResponse) GetMasterPublicKey() []byte {
	if x != nil {
		return x.MasterPublicKey
	}
	return nil
}

func (x *AddTunnelResponse) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *AddTunnelResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

type RemoveTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTunnelRequest) Reset() {
	*x = RemoveTunnelRequest{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTunnelRequest) ProtoMessage() {}

func (x *RemoveTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTunnelRequest.ProtoReflect.Descriptor instead.
func (*RemoveTunnelRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTunnelResponse) Reset() {
	*x = RemoveTunnelResponse{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTunnelResponse) ProtoMessage() {}

func (x *RemoveTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTunnelResponse.ProtoReflect.Descriptor instead.
func (*RemoveTunnelResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveTunnelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateTunnelPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                          // existing tunnel name (e.g. endpoint name "us-01")
	PeerPublicKey []byte                 `protobuf:"bytes,2,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"` // new pubkey (required, 32 bytes)
	BalancerIp    string                 `protobuf:"bytes,3,opt,name=balancer_ip,json=balancerIp,proto3" json:"balancer_ip,omitempty"`            // optional — refresh ECMP mapping
	AllowedIps    []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`            // optional — if non-empty, replace; else keep
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTunnelPeerRequest) Reset() {
	*x = UpdateTunnelPeerRequest{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelPeerRequest) ProtoMessage() {}

func (x *UpdateTunnelPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelPeerRequest.ProtoReflect.Descriptor instead.
func (*UpdateTunnelPeerRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTunnelPeerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTunnelPeerRequest) GetPeerPublicKey() []byte {
	if x != nil {
		return x.PeerPublicKey
	}
	return nil
}

func (x *UpdateTunnelPeerRequest) GetBalancerIp() string {
	if x != nil {
		return x.BalancerIp
	}
	return ""
}

func (x *UpdateTunnelPeerRequest) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

type UpdateTunnelPeerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MasterPublicKey []byte                 `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"` // echo back for caller verification
	Unchanged       bool                   `protobuf:"varint,3,opt,name=unchanged,proto3" json:"unchanged,omitempty"`                                     // true when the new key matches existing (idempotent no-op)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTunnelPeerResponse) Reset() {
	*x = UpdateTunnelPeerResponse{}
	mi := &file_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelPeerResponse) ProtoMessage() {}

func (x *UpdateTunnelPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelPeerResponse.ProtoReflect.Descriptor instead.
func (*UpdateTunnelPeerResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTunnelPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTunnelPeerResponse) GetMasterPublicKey() []byte {
	if x != nil {
		return x.MasterPublicKey
	}
	return nil
}

func (x *UpdateTunnelPeerResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

type TunnelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*TunnelStatus        `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelList) Reset() {
	*x = TunnelList{}
	mi := &file_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelList) ProtoMessage() {}

func (x *TunnelList) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelList.ProtoReflect.Descriptor instead.
func (*TunnelList) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{14}
}

func (x *TunnelList) GetTunnels() []*TunnelStatus {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type AddPeerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey        []byte                 `protobuf:"bytes,2,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Params              *AwgParams             `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	EndpointHost        string                 `protobuf:"bytes,5,opt,name=endpoint_host,json=endpointHost,proto3" json:"endpoint_host,omitempty"`
	PersistentKeepalive int32                  `protobuf:"varint,6,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	TransportSubnet     string                 `protobuf:"bytes,7,opt,name=transport_subnet,json=transportSubnet,proto3" json:"transport_subnet,omitempty"`
	LocalTransportIp    string                 `protobuf:"bytes,8,opt,name=local_transport_ip,json=localTransportIp,proto3" json:"local_transport_ip,omitempty"`
	PeerTransportIp     string                 `protobuf:"bytes,9,opt,name=peer_transport_ip,json=peerTransportIp,proto3" json:"peer_transport_ip,omitempty"`
	BalancerIp          string                 `protobuf:"bytes,10,opt,name=balancer_ip,json=balancerIp,proto3" json:"balancer_ip,omitempty"`
	PeerName            string                 `protobuf:"bytes,11,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`          // master name (on endpoint side) or endpoint name (on master side); used for per-iface routing
	ExtraRoutes         []string               `protobuf:"bytes,12,rep,name=extra_routes,json=extraRoutes,proto3" json:"extra_routes,omitempty"` // extra kernel /32 routes to install via wg-<peer_name> (v1.12.2+: other endpoints reachable via this master)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AddPeerRequest) Reset() {
	*x = AddPeerRequest{}
	mi := &file_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerRequest) ProtoMessage() {}

func (x *AddPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerRequest.ProtoReflect.Descriptor instead.
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{15}
}

func (x *AddPeerRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AddPeerRequest) GetPresharedKey() []byte {
	if x != nil {
		return x.PresharedKey
	}
	return nil
}

func (x *AddPeerRequest) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *AddPeerRequest) GetParams() *AwgParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AddPeerRequest) GetEndpointHost() string {
	if x != nil {
		return x.EndpointHost
	}
	return ""
}

func (x *AddPeerRequest) GetPersistentKeepalive() int32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

func (x *AddPeerRequest) GetTransportSubnet() string {
	if x != nil {
		return x.TransportSubnet
	}
	return ""
}

func (x *AddPeerRequest) GetLocalTransportIp() string {
	if x != nil {
		return x.LocalTransportIp
	}
	return ""
}

func (x *AddPeerRequest) GetPeerTransportIp() string {
	if x != nil {
		return x.PeerTransportIp
	}
	return ""
}

func (x *AddPeerRequest) GetBalancerIp() string {
	if x != nil {
		return x.BalancerIp
	}
	return ""
}

func (x *AddPeerRequest) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *AddPeerRequest) GetExtraRoutes() []string {
	if x != nil {
		return x.ExtraRoutes
	}
	return nil
}

type AddPeerResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EndpointListenPort int32                  `protobuf:"varint,2,opt,name=endpoint_listen_port,json=endpointListenPort,proto3" json:"endpoint_listen_port,omitempty"` // listen port bound by endpoint for this master's wg-<name> iface
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddPeerResponse) Reset() {
	*x = AddPeerResponse{}
	mi := &file_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerResponse) ProtoMessage() {}

func (x *AddPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerResponse.ProtoReflect.Descriptor instead.
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{16}
}

func (x *AddPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPeerResponse) GetEndpointListenPort() int32 {
	if x != nil {
		return x.EndpointListenPort
	}
	return 0
}

type RemovePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{17}
}

func (x *RemovePeerRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{18}
}

func (x *RemovePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerStatus          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{19}
}

func (x *PeerList) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	LastHandshake int64                  `protobuf:"varint,4,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	TxBytes       int64                  `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       int64                  `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{20}
}

func (x *PeerStatus) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PeerStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerStatus) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerStatus) GetLastHandshake() int64 {
	if x != nil {
		return x.LastHandshake
	}
	return 0
}

func (x *PeerStatus) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PeerStatus) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type RotateParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelName    string                 `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	Tier          int32                  `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	NewParams     *AwgParams             `protobuf:"bytes,3,opt,name=new_params,json=newParams,proto3" json:"new_params,omitempty"`
	NewPublicKey  []byte                 `protobuf:"bytes,4,opt,name=new_public_key,json=newPublicKey,proto3" json:"new_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateParamsRequest) Reset() {
	*x = RotateParamsRequest{}
	mi := &file_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateParamsRequest) ProtoMessage() {}

func (x *RotateParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateParamsRequest.ProtoReflect.Descriptor instead.
func (*RotateParamsRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{21}
}

func (x *RotateParamsRequest) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

func (x *RotateParamsRequest) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *RotateParamsRequest) GetNewParams() *AwgParams {
	if x != nil {
		return x.NewParams
	}
	return nil
}

func (x *RotateParamsRequest) GetNewPublicKey() []byte {
	if x != nil {
		return x.NewPublicKey
	}
	return nil
}

type RotateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateParamsResponse) Reset() {
	*x = RotateParamsResponse{}
	mi := &file_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateParamsResponse) ProtoMessage() {}

func (x *RotateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateParamsResponse.ProtoReflect.Descriptor instead.
func (*RotateParamsResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{22}
}

func (x *RotateParamsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RotateParamsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelName    string                 `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParamsRequest) Reset() {
	*x = GetParamsRequest{}
	mi := &file_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamsRequest) ProtoMessage() {}

func (x *GetParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamsRequest.ProtoReflect.Descriptor instead.
func (*GetParamsRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{23}
}

func (x *GetParamsRequest) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

type RotateKeypairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    []byte                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // 32 raw bytes; endpoint persists + rebinds
	TunnelName    string                 `protobuf:"bytes,2,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"` // identifies which endpoint interface to rebind
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeypairRequest) Reset() {
	*x = RotateKeypairRequest{}
	mi := &file_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeypairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeypairRequest) ProtoMessage() {}

func (x *RotateKeypairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeypairRequest.ProtoReflect.Descriptor instead.
func (*RotateKeypairRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{24}
}

func (x *RotateKeypairRequest) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *RotateKeypairRequest) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

type RotateKeypairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPublicKey  []byte                 `protobuf:"bytes,1,opt,name=new_public_key,json=newPublicKey,proto3" json:"new_public_key,omitempty"` // derived from private_key, returned for CLI verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeypairResponse) Reset() {
	*x = RotateKeypairResponse{}
	mi := &file_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeypairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeypairResponse) ProtoMessage() {}

func (x *RotateKeypairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeypairResponse.ProtoReflect.Descriptor instead.
func (*RotateKeypairResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{25}
}

func (x *RotateKeypairResponse) GetNewPublicKey() []byte {
	if x != nil {
		return x.NewPublicKey
	}
	return nil
}

type CaptureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Domains        []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	CountPerDomain int32                  `protobuf:"varint,2,opt,name=count_per_domain,json=countPerDomain,proto3" json:"count_per_domain,omitempty"`
	Schedule       string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`                                 // cron expression or duration (e.g. "0 3 * * *" or "24h")
	RetentionDays  int32                  `protobuf:"varint,4,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"` // how long to keep capture data (0 = no cleanup)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{26}
}

func (x *CaptureRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *CaptureRequest) GetCountPerDomain() int32 {
	if x != nil {
		return x.CountPerDomain
	}
	return 0
}

func (x *CaptureRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CaptureRequest) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type CaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CapturedCount int32                  `protobuf:"varint,2,opt,name=captured_count,json=capturedCount,proto3" json:"captured_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{27}
}

func (x *CaptureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CaptureResponse) GetCapturedCount() int32 {
	if x != nil {
		return x.CapturedCount
	}
	return 0
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,3,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	Tunnels       []*TunnelStatus        `protobuf:"bytes,4,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{28}
}

func (x *NodeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeStatus) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *NodeStatus) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *NodeStatus) GetTunnels() []*TunnelStatus {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *NodeStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type TunnelStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,2,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	Healthy       bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LastHandshake int64                  `protobuf:"varint,4,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	TxBytes       int64                  `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       int64                  `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	LastRotation  string                 `protobuf:"bytes,7,opt,name=last_rotation,json=lastRotation,proto3" json:"last_rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelStatus) Reset() {
	*x = TunnelStatus{}
	mi := &file_types_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStatus) ProtoMessage() {}

func (x *TunnelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStatus.ProtoReflect.Descriptor instead.
func (*TunnelStatus) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{29}
}

func (x *TunnelStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelStatus) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *TunnelStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *TunnelStatus) GetLastHandshake() int64 {
	if x != nil {
		return x.LastHandshake
	}
	return 0
}

func (x *TunnelStatus) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *TunnelStatus) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *TunnelStatus) GetLastRotation() string {
	if x != nil {
		return x.LastRotation
	}
	return ""
}

type RouteTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteEntry          `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTable) Reset() {
	*x = RouteTable{}
	mi := &file_types_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTable) ProtoMessage() {}

func (x *RouteTable) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTable.ProtoReflect.Descriptor instead.
func (*RouteTable) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{30}
}

func (x *RouteTable) GetRoutes() []*RouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ViaInterface  string                 `protobuf:"bytes,2,opt,name=via_interface,json=viaInterface,proto3" json:"via_interface,omitempty"`
	ViaOverlayIp  string                 `protobuf:"bytes,3,opt,name=via_overlay_ip,json=viaOverlayIp,proto3" json:"via_overlay_ip,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_types_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{31}
}

func (x *RouteEntry) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteEntry) GetViaInterface() string {
	if x != nil {
		return x.ViaInterface
	}
	return ""
}

func (x *RouteEntry) GetViaOverlayIp() string {
	if x != nil {
		return x.ViaOverlayIp
	}
	return ""
}

func (x *RouteEntry) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RouteEntry) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	TunnelHealth  []*TunnelHealth        `protobuf:"bytes,2,rep,name=tunnel_health,json=tunnelHealth,proto3" json:"tunnel_health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_types_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{32}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetTunnelHealth() []*TunnelHealth {
	if x != nil {
		return x.TunnelHealth
	}
	return nil
}

type TunnelHealth struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Healthy             bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LastCheckMs         int64                  `protobuf:"varint,3,opt,name=last_check_ms,json=lastCheckMs,proto3" json:"last_check_ms,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,4,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TunnelHealth) Reset() {
	*x = TunnelHealth{}
	mi := &file_types_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelHealth) ProtoMessage() {}

func (x *TunnelHealth) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelHealth.ProtoReflect.Descriptor instead.
func (*TunnelHealth) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{33}
}

func (x *TunnelHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *TunnelHealth) GetLastCheckMs() int64 {
	if x != nil {
		return x.LastCheckMs
	}
	return 0
}

func (x *TunnelHealth) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

type TransportPeerState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                       // peer name (endpoint or master name)
	PublicKeyHex      string                 `protobuf:"bytes,2,opt,name=public_key_hex,json=publicKeyHex,proto3" json:"public_key_hex,omitempty"`                 // runtime public key (from live wg/tunnel state)
	AllowedIps        []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`                         // runtime allowed IP CIDRs (from live peer manager)
	LastHandshakeUnix int64                  `protobuf:"varint,4,opt,name=last_handshake_unix,json=lastHandshakeUnix,proto3" json:"last_handshake_unix,omitempty"` // Unix timestamp of last WireGuard handshake (0 = never)
	DiskPublicKeyHex  string                 `protobuf:"bytes,5,opt,name=disk_public_key_hex,json=diskPublicKeyHex,proto3" json:"disk_public_key_hex,omitempty"`   // disk public key (from transport.yml); empty = same as runtime or unknown
	DiskAllowedIps    []string               `protobuf:"bytes,6,rep,name=disk_allowed_ips,json=diskAllowedIps,proto3" json:"disk_allowed_ips,omitempty"`           // disk allowed IPs (from transport.yml); empty = same as runtime
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransportPeerState) Reset() {
	*x = TransportPeerState{}
	mi := &file_types_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportPeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportPeerState) ProtoMessage() {}

func (x *TransportPeerState) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportPeerState.ProtoReflect.Descriptor instead.
func (*TransportPeerState) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{34}
}

func (x *TransportPeerState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransportPeerState) GetPublicKeyHex() string {
	if x != nil {
		return x.PublicKeyHex
	}
	return ""
}

func (x *TransportPeerState) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *TransportPeerState) GetLastHandshakeUnix() int64 {
	if x != nil {
		return x.LastHandshakeUnix
	}
	return 0
}

func (x *TransportPeerState) GetDiskPublicKeyHex() string {
	if x != nil {
		return x.DiskPublicKeyHex
	}
	return ""
}

func (x *TransportPeerState) GetDiskAllowedIps() []string {
	if x != nil {
		return x.DiskAllowedIps
	}
	return nil
}

type TransportStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,3,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	Peers         []*TransportPeerState  `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportStateResponse) Reset() {
	*x = TransportStateResponse{}
	mi := &file_types_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportStateResponse) ProtoMessage() {}

func (x *TransportStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportStateResponse.ProtoReflect.Descriptor instead.
func (*TransportStateResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{35}
}

func (x *TransportStateResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TransportStateResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TransportStateResponse) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

func (x *TransportStateResponse) GetPeers() []*TransportPeerState {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\aawgmesh\"\a\n" +
	"\x05Empty\"\x93\x02\n" +
	"\tAwgParams\x12\x0e\n" +
	"\x02jc\x18\x01 \x01(\x05R\x02jc\x12\x12\n" +
	"\x04jmin\x18\x02 \x01(\x05R\x04jmin\x12\x12\n" +
	"\x04jmax\x18\x03 \x01(\x05R\x04jmax\x12\x0e\n" +
	"\x02s1\x18\x04 \x01(\x05R\x02s1\x12\x0e\n" +
	"\x02s2\x18\x05 \x01(\x05R\x02s2\x12\x0e\n" +
	"\x02s3\x18\x06 \x01(\x05R\x02s3\x12\x0e\n" +
	"\x02s4\x18\a \x01(\x05R\x02s4\x12\x0e\n" +
	"\x02h1\x18\b \x01(\x05R\x02h1\x12\x0e\n" +
	"\x02h2\x18\t \x01(\x05R\x02h2\x12\x0e\n" +
	"\x02h3\x18\n" +
	" \x01(\x05R\x02h3\x12\x0e\n" +
	"\x02h4\x18\v \x01(\x05R\x02h4\x12\x0e\n" +
	"\x02i1\x18\f \x01(\tR\x02i1\x12\x0e\n" +
	"\x02i2\x18\r \x01(\tR\x02i2\x12\x0e\n" +
	"\x02i3\x18\x0e \x01(\tR\x02i3\x12\x0e\n" +
	"\x02i4\x18\x0f \x01(\tR\x02i4\x12\x0e\n" +
	"\x02i5\x18\x10 \x01(\tR\x02i5\"\x9d\x01\n" +
	"\n" +
	"NodeConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x03 \x01(\tR\toverlayIp\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\x05R\n" +
	"listenPort\x12'\n" +
	"\x05peers\x18\x05 \x03(\v2\x11.awgmesh.PeerSpecR\x05peers\"\xf3\x01\n" +
	"\bPeerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rendpoint_host\x18\x02 \x01(\tR\fendpointHost\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x03 \x01(\tR\toverlayIp\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12#\n" +
	"\rpreshared_key\x18\x05 \x01(\fR\fpresharedKey\x12\x1f\n" +
	"\vallowed_ips\x18\x06 \x03(\tR\n" +
	"allowedIps\x12*\n" +
	"\x06params\x18\a \x01(\v2\x12.awgmesh.AwgParamsR\x06params\"\x8b\x01\n" +
	"\vInitRequest\x12\x17\n" +
	"\aca_cert\x18\x01 \x01(\fR\x06caCert\x12\x1b\n" +
	"\tnode_cert\x18\x02 \x01(\fR\bnodeCert\x12\x19\n" +
	"\bnode_key\x18\x03 \x01(\fR\anodeKey\x12+\n" +
	"\x06config\x18\x04 \x01(\v2\x13.awgmesh.NodeConfigR\x06config\"j\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fnode_public_key\x18\x02 \x01(\fR\rnodePublicKey\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\":\n" +
	"\x12RotateTokenRequest\x12$\n" +
	"\x0enew_token_hash\x18\x01 \x01(\tR\fnewTokenHash\"/\n" +
	"\x13RotateTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe4\x03\n" +
	"\x10AddTunnelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rendpoint_host\x18\x02 \x01(\tR\fendpointHost\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x03 \x01(\tR\toverlayIp\x12\x1f\n" +
	"\vbalancer_ip\x18\x04 \x01(\tR\n" +
	"balancerIp\x12&\n" +
	"\x0fpeer_public_key\x18\x05 \x01(\fR\rpeerPublicKey\x12#\n" +
	"\rpreshared_key\x18\x06 \x01(\fR\fpresharedKey\x12*\n" +
	"\x06params\x18\a \x01(\v2\x12.awgmesh.AwgParamsR\x06params\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12\x16\n" +
	"\x06backup\x18\t \x01(\bR\x06backup\x12)\n" +
	"\x10transport_subnet\x18\n" +
	" \x01(\tR\x0ftransportSubnet\x12.\n" +
	"\x13master_transport_ip\x18\v \x01(\tR\x11masterTransportIp\x122\n" +
	"\x15endpoint_transport_ip\x18\f \x01(\tR\x13endpointTransportIp\x12\x1f\n" +
	"\vallowed_ips\x18\r \x03(\tR\n" +
	"allowedIps\"\xa1\x01\n" +
	"\x11AddTunnelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x11master_public_key\x18\x02 \x01(\fR\x0fmasterPublicKey\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\x05R\n" +
	"listenPort\")\n" +
	"\x13RemoveTunnelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x14RemoveTunnelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x97\x01\n" +
	"\x17UpdateTunnelPeerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0fpeer_public_key\x18\x02 \x01(\fR\rpeerPublicKey\x12\x1f\n" +
	"\vbalancer_ip\x18\x03 \x01(\tR\n" +
	"balancerIp\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\"~\n" +
	"\x18UpdateTunnelPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\x11master_public_key\x18\x02 \x01(\fR\x0fmasterPublicKey\x12\x1c\n" +
	"\tunchanged\x18\x03 \x01(\bR\tunchanged\"=\n" +
	"\n" +
	"TunnelList\x12/\n" +
	"\atunnels\x18\x01 \x03(\v2\x15.awgmesh.TunnelStatusR\atunnels\"\xdf\x03\n" +
	"\x0eAddPeerRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12#\n" +
	"\rpreshared_key\x18\x02 \x01(\fR\fpresharedKey\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12*\n" +
	"\x06params\x18\x04 \x01(\v2\x12.awgmesh.AwgParamsR\x06params\x12#\n" +
	"\rendpoint_host\x18\x05 \x01(\tR\fendpointHost\x121\n" +
	"\x14persistent_keepalive\x18\x06 \x01(\x05R\x13persistentKeepalive\x12)\n" +
	"\x10transport_subnet\x18\a \x01(\tR\x0ftransportSubnet\x12,\n" +
	"\x12local_transport_ip\x18\b \x01(\tR\x10localTransportIp\x12*\n" +
	"\x11peer_transport_ip\x18\t \x01(\tR\x0fpeerTransportIp\x12\x1f\n" +
	"\vbalancer_ip\x18\n" +
	" \x01(\tR\n" +
	"balancerIp\x12\x1b\n" +
	"\tpeer_name\x18\v \x01(\tR\bpeerName\x12!\n" +
	"\fextra_routes\x18\f \x03(\tR\vextraRoutes\"]\n" +
	"\x0fAddPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x14endpoint_listen_port\x18\x02 \x01(\x05R\x12endpointListenPort\"2\n" +
	"\x11RemovePeerRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\".\n" +
	"\x12RemovePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\bPeerList\x12)\n" +
	"\x05peers\x18\x01 \x03(\v2\x13.awgmesh.PeerStatusR\x05peers\"\xc5\x01\n" +
	"\n" +
	"PeerStatus\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12%\n" +
	"\x0elast_handshake\x18\x04 \x01(\x03R\rlastHandshake\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x03R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x03R\arxBytes\"\xa3\x01\n" +
	"\x13RotateParamsRequest\x12\x1f\n" +
	"\vtunnel_name\x18\x01 \x01(\tR\n" +
	"tunnelName\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\x05R\x04tier\x121\n" +
	"\n" +
	"new_params\x18\x03 \x01(\v2\x12.awgmesh.AwgParamsR\tnewParams\x12$\n" +
	"\x0enew_public_key\x18\x04 \x01(\fR\fnewPublicKey\"J\n" +
	"\x14RotateParamsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x10GetParamsRequest\x12\x1f\n" +
	"\vtunnel_name\x18\x01 \x01(\tR\n" +
	"tunnelName\"X\n" +
	"\x14RotateKeypairRequest\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\fR\n" +
	"privateKey\x12\x1f\n" +
	"\vtunnel_name\x18\x02 \x01(\tR\n" +
	"tunnelName\"=\n" +
	"\x15RotateKeypairResponse\x12$\n" +
	"\x0enew_public_key\x18\x01 \x01(\fR\fnewPublicKey\"\x97\x01\n" +
	"\x0eCaptureRequest\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\x12(\n" +
	"\x10count_per_domain\x18\x02 \x01(\x05R\x0ecountPerDomain\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12%\n" +
	"\x0eretention_days\x18\x04 \x01(\x05R\rretentionDays\"R\n" +
	"\x0fCaptureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ecaptured_count\x18\x02 \x01(\x05R\rcapturedCount\"\x9c\x01\n" +
	"\n" +
	"NodeStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x03 \x01(\tR\toverlayIp\x12/\n" +
	"\atunnels\x18\x04 \x03(\v2\x15.awgmesh.TunnelStatusR\atunnels\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\"\xdd\x01\n" +
	"\fTunnelStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x02 \x01(\tR\toverlayIp\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12%\n" +
	"\x0elast_handshake\x18\x04 \x01(\x03R\rlastHandshake\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x03R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x03R\arxBytes\x12#\n" +
	"\rlast_rotation\x18\a \x01(\tR\flastRotation\"9\n" +
	"\n" +
	"RouteTable\x12+\n" +
	"\x06routes\x18\x01 \x03(\v2\x13.awgmesh.RouteEntryR\x06routes\"\xa9\x01\n" +
	"\n" +
	"RouteEntry\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12#\n" +
	"\rvia_interface\x18\x02 \x01(\tR\fviaInterface\x12$\n" +
	"\x0evia_overlay_ip\x18\x03 \x01(\tR\fviaOverlayIp\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"f\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12:\n" +
	"\rtunnel_health\x18\x02 \x03(\v2\x15.awgmesh.TunnelHealthR\ftunnelHealth\"\x93\x01\n" +
	"\fTunnelHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\"\n" +
	"\rlast_check_ms\x18\x03 \x01(\x03R\vlastCheckMs\x121\n" +
	"\x14consecutive_failures\x18\x04 \x01(\x05R\x13consecutiveFailures\"\xf8\x01\n" +
	"\x12TransportPeerState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x0epublic_key_hex\x18\x02 \x01(\tR\fpublicKeyHex\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12.\n" +
	"\x13last_handshake_unix\x18\x04 \x01(\x03R\x11lastHandshakeUnix\x12-\n" +
	"\x13disk_public_key_hex\x18\x05 \x01(\tR\x10diskPublicKeyHex\x12(\n" +
	"\x10disk_allowed_ips\x18\x06 \x03(\tR\x0ediskAllowedIps\"\x9b\x01\n" +
	"\x16TransportStateResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x03 \x01(\tR\toverlayIp\x121\n" +
	"\x05peers\x18\x04 \x03(\v2\x1b.awgmesh.TransportPeerStateR\x05peersB2Z0github.com/coonfuuseed-paandaa/awg-mesh/v2/protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_types_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: awgmesh.Empty
	(*AwgParams)(nil),                // 1: awgmesh.AwgParams
	(*NodeConfig)(nil),               // 2: awgmesh.NodeConfig
	(*PeerSpec)(nil),                 // 3: awgmesh.PeerSpec
	(*InitRequest)(nil),              // 4: awgmesh.InitRequest
	(*InitResponse)(nil),             // 5: awgmesh.InitResponse
	(*RotateTokenRequest)(nil),       // 6: awgmesh.RotateTokenRequest
	(*RotateTokenResponse)(nil),      // 7: awgmesh.RotateTokenResponse
	(*AddTunnelRequest)(nil),         // 8: awgmesh.AddTunnelRequest
	(*AddTunnelResponse)(nil),        // 9: awgmesh.AddTunnelResponse
	(*RemoveTunnelRequest)(nil),      // 10: awgmesh.RemoveTunnelRequest
	(*RemoveTunnelResponse)(nil),     // 11: awgmesh.RemoveTunnelResponse
	(*UpdateTunnelPeerRequest)(nil),  // 12: awgmesh.UpdateTunnelPeerRequest
	(*UpdateTunnelPeerResponse)(nil), // 13: awgmesh.UpdateTunnelPeerResponse
	(*TunnelList)(nil),               // 14: awgmesh.TunnelList
	(*AddPeerRequest)(nil),           // 15: awgmesh.AddPeerRequest
	(*AddPeerResponse)(nil),          // 16: awgmesh.AddPeerResponse
	(*RemovePeerRequest)(nil),        // 17: awgmesh.RemovePeerRequest
	(*RemovePeerResponse)(nil),       // 18: awgmesh.RemovePeerResponse
	(*PeerList)(nil),                 // 19: awgmesh.PeerList
	(*PeerStatus)(nil),               // 20: awgmesh.PeerStatus
	(*RotateParamsRequest)(nil),      // 21: awgmesh.RotateParamsRequest
	(*RotateParamsResponse)(nil),     // 22: awgmesh.RotateParamsResponse
	(*GetParamsRequest)(nil),         // 23: awgmesh.GetParamsRequest
	(*RotateKeypairRequest)(nil),     // 24: awgmesh.RotateKeypairRequest
	(*RotateKeypairResponse)(nil),    // 25: awgmesh.RotateKeypairResponse
	(*CaptureRequest)(nil),           // 26: awgmesh.CaptureRequest
	(*CaptureResponse)(nil),          // 27: awgmesh.CaptureResponse
	(*NodeStatus)(nil),               // 28: awgmesh.NodeStatus
	(*TunnelStatus)(nil),             // 29: awgmesh.TunnelStatus
	(*RouteTable)(nil),               // 30: awgmesh.RouteTable
	(*RouteEntry)(nil),               // 31: awgmesh.RouteEntry
	(*HealthResponse)(nil),           // 32: awgmesh.HealthResponse
	(*TunnelHealth)(nil),             // 33: awgmesh.TunnelHealth
	(*TransportPeerState)(nil),       // 34: awgmesh.TransportPeerState
	(*TransportStateResponse)(nil),   // 35: awgmesh.TransportStateResponse
}
var file_types_proto_depIdxs = []int32{
	3,  // 0: awgmesh.NodeConfig.peers:type_name -> awgmesh.PeerSpec
	1,  // 1: awgmesh.PeerSpec.params:type_name -> awgmesh.AwgParams
	2,  // 2: awgmesh.InitRequest.config:type_name -> awgmesh.NodeConfig
	1,  // 3: awgmesh.AddTunnelRequest.params:type_name -> awgmesh.AwgParams
	29, // 4: awgmesh.TunnelList.tunnels:type_name -> awgmesh.TunnelStatus
	1,  // 5: awgmesh.AddPeerRequest.params:type_name -> awgmesh.AwgParams
	20, // 6: awgmesh.PeerList.peers:type_name -> awgmesh.PeerStatus
	1,  // 7: awgmesh.RotateParamsRequest.new_params:type_name -> awgmesh.AwgParams
	29, // 8: awgmesh.NodeStatus.tunnels:type_name -> awgmesh.TunnelStatus
	31, // 9: awgmesh.RouteTable.routes:type_name -> awgmesh.RouteEntry
	33, // 10: awgmesh.HealthResponse.tunnel_health:type_name -> awgmesh.TunnelHealth
	34, // 11: awgmesh.TransportStateResponse.peers:type_name -> awgmesh.TransportPeerState
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
